/** @type { importCharacterConfig[`character`] } */
const characters = {
	Enrico_Pucci_yzs: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		isUnseen: true,
		skills: ["speedup_yzs", "create_newworld_yzs"],
		names: "恩里克普奇",
		img: "extension/一中杀/image/Enrico_Pucci_yzs.png",
	},

	YouBeier_yzs: {
		sex: "female",
		group: "wu",
		hp: 4,
		skills: ["suixin_yzs", "wangzhan_yzs"],
		names: "尤贝尔",
		img: "extension/一中杀/image/YouBeier_yzs.png",
	},

	LU_Captain_xiangsiniao_yzs: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["jiangli_yzs"],
		names: "奖励队长",
		img: "extension/一中杀/image/LU_Captain_xiangsiniao_yzs.png",
	},

	HuangJOJO_yzs: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["nengliyoudaxiao_yzs", "huangjinzhixing_yzs"],
		names: "建军",
		img: "extension/一中杀/image/HuangJOJO_yzs.png",
	},

	JiLiangJiTao_yzs: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["first_bomb_yzs", "BitetheDust_yzs"],
		names: "吉良吉涛",
		img: "extension/一中杀/image/JiLiangJiTao_yzs.png",
		BGM: "Great Days",
	},

	shenChangzhang_yzs: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["tudao_yzs", "tuzai_yzs"],
		names: "厂长",
		img: "extension/一中杀/image/shenChangzhang_yzs.png",
	},

	shenfu_Limu_yzs: {
		sex: "male",
		group: "wei",
		hp: 5,
		skills: ["yifuzhiming_yzs"],
		names: "李木",
		img: "extension/一中杀/image/shenfu_Limu_yzs.png",
	},

	WZZS_lilixin_yzs: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["zhengli_yzs", "zhujiu_yzs"],
		names: "李励薪",
		img: "extension/一中杀/image/WZZS_lilixin_yzs.png",
		dieAudios: ["ext:一中杀/audio/die/WZZS_lilixin_yzs.mp3"],
	},

	changzhang_yzs: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["yangzhu_yzs", "lastclass_yzs"],
		names: "熊伯",
		img: "extension/一中杀/image/changzhang_yzs.png",
	},

	jealous_witch_yzs: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["love_circle_yzs", "fantasy_train_yzs"],
		names: "W",
		img: "extension/一中杀/image/jealous_witch_yzs.png",
		dieAudios: ["ext:一中杀/audio/die/jealous_witch_yzs.mp3"],
	},

	lianhua_yzs: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["tears_yzs", "wanhua_mirror_yzs", "gathering_hopes_yzs"],
		names: "莲华",
		img: "extension/一中杀/image/lianhua_yzs.png"
	},

	hunziKing_yzs: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["copywork_yzs", "drawfish_yzs"],
		names: "余东阳",
		img: "extension/一中杀/image/hunziKing_yzs.png"
	},

	wuyingYFY_yzs: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["wuying_yzs", "shadowattack_yzs", "kill_yzs", "toutianhuanri_yzs"],
		names: "翼飞羽",
		img: "extension/一中杀/image/wuyingYFY_yzs.png",
		dieAudios: ["ext:一中杀/audio/die/wuyingYFY_yzs.mp3"],
	},

	Cana_yzs: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["blessing_yzs", "HolyBlessing_yzs"],
		names: "迦南",
		img: "extension/一中杀/image/Cana_yzs.png",
		dieAudios: ["ext:一中杀/audio/die/Cana_yzs.mp3"],
		DamageAudio: 3,
		DamageAudio2: 2,
	},

	Lazy_twins_yzs: {
		sex: "female",
		group: "qun",
		hp: 5,
		skills: ["HuanMeng_yzs", "DreamTwins_yzs"],
		names: "冬&祺",
		img: "extension/一中杀/image/Lazy_twins_yzs.png"
	},

	Remilia_Scarlet_yzs: {
		sex: "female",
		group: "shu",
		hp: 5,
		skills: ["liuwangnvshiqu_yzs", "Gungnell_yzs", "VampireKiss_yzs"],
		names: "蕾米莉亚",
		img: "extension/一中杀/image/Remilia_Scarlet_yzs.png",
		Fuka: 3,
	},

	chenxu_yzs: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["angryXU_yzs", "sheshen_yzs", "undyinghero_yzs"],
		names: "嗔嘘",
		img: "extension/一中杀/image/chenxu_yzs.png",
	},

	AngryFeng_yzs: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 6,
		skills: ["brokenheart_yzs", "yotouFeng_yzs", "yotouXi_yzs"],
		names: "冯|克洛文凭",
		img: "extension/一中杀/image/AngryFeng_yzs.png",
	},

	Unbelieve_xiangzi_yzs: {
		sex: "male",
		group: "shu",
		hp: 1,
		skills: ["brokenweapon_yzs", "Unbelieve_yzs", "judgeEyes_yzs"],
		names: "翔子",
		img: "extension/一中杀/image/Unbelieve_xiangzi_yzs.png",
	},

	yagamiLight_yzs: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["kila_yzs", "zhitui_yzs", "juece_yzs", "xinsega_yzs"],
		names: "夜神|月",
		img: "extension/一中杀/image/yagamiLight_yzs.png",
	},

	Halo_yzs: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["princetwittering_yzs"],
		names: "璐璐杨|哈洛",
		img: "extension/一中杀/image/Halo_yzs.png",
		dieAudios: ["ext:一中杀/audio/die/Halo_yzs.mp3"],
	},

	Noir_yzs: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["buxudong_yzs", "haixiangpao_yzs"],
		names: "诺艾尔",
		img: "extension/一中杀/image/Noir_yzs.png",
	},

	lianjinzhencai_yzs: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["mysterydrug_yzs", "burnlife_yzs", "shikuang_yzs"],
		names: "馏蒸材",
		img: "extension/一中杀/image/lianjinzhencai_yzs.png",
	},

	weaponmaster_yzs: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["yinju_yzs", "badaozhan_yzs", "wuqizhangkong_yzs"],
		names: "车杳",
		img: "extension/一中杀/image/weaponmaster_yzs.png",
		dieAudios: ["ext:一中杀/audio/die/weaponmaster_yzs.mp3"],
	},

	SukunaShinmyoumaru_yzs: {
		sex: "female",
		group: "shu",
		hp: 6,
		skills: ["yicunfashi_yzs", "bianda_yzs", "dapanxiaopan_yzs", "jieyicunfashi_yzs"],
		names: "少名针妙丸",
		img: "extension/一中杀/image/SukunaShinmyoumaru_yzs.png",
		Fuka: 3,
		BGM: "輝く針の小人族　～ Little Princess",
	},

	Cirno_yzs: {
		sex: "female",
		group: "wei",
		hp: 4,
		skills: ["perfectArithmetic_yzs", "perfectFreeze_yzs"],
		names: "琪露诺",
		img: "extension/一中杀/image/Cirno_yzs.png",
		Fuka: 3,
	},

	Patchouli_Knowledge_yzs: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["steadyLibrary_yzs", "wiseStone_yzs", "silentSelene_yzs"],
		names: "帕秋莉",
		img: "extension/一中杀/image/Patchouli_Knowledge_yzs.png",
		Fuka: 2,
	},

	Yorigami_twins_yzs: {
		sex: "female",
		group: "wei",
		hp: 4,
		skills: ["bubbleQueen_yzs", "finances_yzs", "Mischance_Scatter_yzs"],
		names: "女苑&紫苑",
		img: "extension/一中杀/image/Yorigami_twins_yzs.png",
		Fuka: 4,
		BGM: "今宵は飄逸なエゴイスト",
	},

	Ibuki_Suika_yzs: {
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 4,
		skills: ["mengmengjiugui_yzs", "yichuirang_yzs", "yunjiwusan_yzs"],
		names: "伊吹萃香",
		img: "extension/一中杀/image/Ibuki_Suika_yzs.png",
		Fuka: 3,
	},

	Zbro_yzs: {
		sex: "male",
		group: "wei",
		hp: 5,
		skills: ["pinfanshijie_yzs", "Versailles_yzs", "Zkill_yzs"],
		names: "Z哥",
		img: "extension/一中杀/image/Zbro_yzs.png",
	},

	toothFairy_yzs: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["FairyInNight_yzs"],
		names: "牙仙",
		img: "extension/一中杀/image/toothFairy_yzs.png",
		DamageAudio: 2,
	},

	RatTiger_yzs: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["juBao_yzs", "tanBao_yzs", "baoTa_yzs", "weiGuang_yzs"],
		names: "娜兹玲&寅丸星",
		img: "extension/一中杀/image/RatTiger_yzs.png",
		Fuka: 4,
	},

	Floris_yzs: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["tuiyidele_yzs", "daqijingshen_yzs"],
		names: "芙洛玛西斯",
		img: "extension/一中杀/image/Floris_yzs.png",
	},

	ChainsawCock_yzs: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["jixiong_yzs", "geju_yzs", "fengnong_yzs"],
		names: "鲁日立",
		img: "extension/一中杀/image/ChainsawCock_yzs.png",
	},

	Chino_yzs: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["xueke_yzs", "kexue_yzs", "yuyan_yzs", "aiqi_yzs"],
		names: "琪诺",
		img: "extension/一中杀/image/Chino_yzs.png",
		dieAudios: ["ext:一中杀/audio/die/Chino_yzs.mp3"],
		DamageAudio: 3,
		DamageAudio2: 2,
	},

	Seele_Vollerei_yzs: {
		sex: "female",
		group: "wei",
		hp: 1,
		skills: ["shuangsheng_yzs", "chuangsheng_yzs", "xieshengzhijing_yzs", "niworuyi_yzs"],
		names: "希儿",
		img: "extension/一中杀/image/Seele_Vollerei_yzs.png",
	},

	Qianmian_Limu_yzs: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["aoman_yzs", "qianmian_yzs", "tiance_yzs", "shenzhiyishou_yzs"],
		names: "李暮",
		img: "extension/一中杀/image/Qianmian_Limu_yzs.png",
		dieAudios: ["ext:一中杀/audio/die/Qianmian_Limu_yzs.mp3"],
	},

	Fern_yzs: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["Zoltraak_yzs", "Defend_yzs", "suyin_yzs"],
		names: "菲伦",
		img: "extension/一中杀/image/Fern_yzs.png",
		BGM: "Zoltraak",
	},

	Marisa_yzs: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["MasterSpark_yzs", "StardustReverie_yzs", "IllusionStar_yzs"],
		names: "魔理沙",
		img: "extension/一中杀/image/Marisa_yzs.png",
		Fuka: 3,
		BGM: "神々が恋した幻想郷",
	},

	Tenshi_yzs: {
		sex: "female",
		group: "wei",
		hp: 1,
		skills: ["Wonderful_Heaven_yzs", "tiandikaipi_yzs", "guruojintangtao_yzs", "feixiangtian_yzs"],
		names: "比那名居天子",
		img: "extension/一中杀/image/Tenshi_yzs.png",
		Fuka: 4,
		BGM: "東方緋想天 (Arrange Version) _ あきやまうに",
	},

	Onozuka_Komachi_yzs: {
		sex: "female",
		group: "shu",
		hp: 5,
		skills: ["bachongwuzhongdu_yzs", "hunliliandao_yzs", "Higan_Retour_yzs"],
		names: "小野塚小町",
		img: "extension/一中杀/image/Onozuka_Komachi_yzs.png",
		Fuka: 5,
	},

	NatsukiSubaru_yzs: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["nuoruo_yzs", "monvdeyuxiang_yzs", "siwanghuigui_yzs"],
		names: "菜月昴",
		img: "extension/一中杀/image/NatsukiSubaru_yzs.png",
		BGM: "STYX HELIX",
	},

	EastYang_yzs: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["zhanqi_yzs", "KingsHand_yzs"],
		names: "伊斯特|阳",
		img: "extension/一中杀/image/EastYang_yzs.png",
	},

	Denglanxitaro_yzs: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["langhua_yzs", "langren_yzs"],
		names: "邓懒 夕太郎",
		img: "extension/一中杀/image/Denglanxitaro_yzs.png",
		dieAudios: ["ext:一中杀/audio/die/Denglanxitaro_yzs.mp3"],
	},

	Zhonghuang_yzs: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["bushi_yzs", "shengxin_yzs", "tairan_yzs"],
		names: "钟皇",
		img: "extension/一中杀/image/Zhonghuang_yzs.png",
		dieAudios: ["ext:一中杀/audio/die/Zhonghuang_yzs.mp3"],
	},

	Xiangbolin_yzs: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["shiyi_yzs", "tiaoxiang_yzs"],
		names: "香波霖",
		img: "extension/一中杀/image/Xiangbolin_yzs.png",
		dieAudios: ["ext:一中杀/audio/die/Xiangbolin_yzs.mp3"],
	},

	PhantomEnsemble_yzs: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["xiezou_yzs", "yuetuan_yzs"],
		names: "骚灵三姐妹",
		img: "extension/一中杀/image/PhantomEnsemble_yzs.png",
		BGM: "神々が恋した幻想郷",
	},

	cunhe_yzs: {
		sex: "female",
		group: "wei",
		hp: 4,
		skills: ["chengfengpolang_yzs", "yangfanqihang_yzs"],
		names: "远舟村贺",
		img: "extension/一中杀/image/cunhe_yzs.png",
		dieAudios: ["ext:一中杀/audio/die/cunhe_yzs.mp3"],
		DamageAudio: 3,
		DamageAudio2: 2,
	},

	Yuyuko_yzs: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["wangling_yzs", "fanhundie_yzs", "yousi_yzs"],
		names: "西行寺幽幽子",
		img: "extension/一中杀/image/Yuyuko_yzs.png",
		Fuka: 2,
		BGM: "メグルユメ",
	},

	tangjiheChao_yzs: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["wuwei_yzs", "yingyongjuedou_yzs", "qishidao_yzs"],
		names: "涂 唐吉诃超",
		img: "extension/一中杀/image/tangjiheChao_yzs.png",
	},

	LilyWhite_yzs: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["callSpring_yzs", "SurpriseSpring_yzs"],
		names: "莉莉霍瓦特",
		img: "extension/一中杀/image/LilyWhite_yzs.png",
		BGM: "神々が恋した幻想郷",
	},

	AdmiredWitch_yzs: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["quanbing_yzs", "shenshu_yzs", "jinzhou_yzs"],
		names: "爱诺琪丝",
		img: "extension/一中杀/image/AdmiredWitch_yzs.png",
	},

	IceGirl_yzs: {
		sex: "female",
		group: "wei",
		hp: 4,
		skills: ["bingjie_yzs", "bingpo_yzs", "IceAge_yzs"],
		names: "钟仪宣",
		img: "extension/一中杀/image/IceGirl_yzs.png",
	},

	Innocent_xiangzi_yzs: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["chunzhen_yzs", "zhenwu_yzs", "zhenyi_yzs"],
		names: "翔子",
		img: "extension/一中杀/image/Innocent_xiangzi_yzs.png",
	},

	TimeThief_yzs: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["thief_yzs", "qianying_yzs"],
		names: "盘面塑造者",
		img: "extension/一中杀/image/TimeThief_yzs.png",
	},

	Patriot_yzs: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["buxijinjun_yzs", "huimiezitai_yzs", "jiandun_yzs"],
		names: "博卓卡斯替",
		img: "extension/一中杀/image/Patriot_yzs.png",
		BGM: "End Like This",
	},

	DreamWitch_yzs: {
		sex: "female",
		group: "wei",
		hp: 4,
		skills: ["mengliao_yzs", "qimeng_yzs", "mengmie_yzs"],
		names: "肖",
		img: "extension/一中杀/image/DreamWitch_yzs.png",
	},

	DimensionWitch_yzs: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["tiangongkaiwu_yzs", "xunyou_yzs", "gongyin_yzs","ciyuanchaoyue_yzs"],
		names: "许如荧",
		img: "extension/一中杀/image/DimensionWitch_yzs.png",
	},

	SixSoulsFlowey_yzs: {
		sex: "none",
		group: "shen",
		hp: 6666,
		skills: ["SSF_determination_yzs", "SixSouls_yzs", "SSF_Nightmare_yzs"],
		names: "六魂花",
		img: "extension/一中杀/image/SSF_Nightmare_yzs.gif",
	},

	FailedFlowey_yzs: {
		sex: "none",
		group: "qun",
		isUnseen:true,
		hp: 4,
		skills: ["Run_yzs"],
		names: "小花",
		img: "extension/一中杀/image/FailedFlowey_yzs.png",
	},

	QiGongMaster_yzs: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["qigong_yzs", "taiji_yzs", "chongxu_yzs"],
		names: "鹤元海",
		img: "extension/一中杀/image/QiGongMaster_yzs.png",
	},

	yinBochen_yzs: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["ErWangSaid_yzs", "ErWangPlay_yzs", "ErWangLock_yzs"],
		names: "殷Bo琛",
		img: "extension/一中杀/image/yinBochen_yzs.png",
	},

	Akyuu_yzs: {
		sex: "female",
		group: "shu",
		hp: 1,
		skills: ["qiuwen_yzs",  "zhuanshi_yzs"],
		names: "稗田阿求",
		img: "extension/一中杀/image/Akyuu_yzs.png",
	},

	APPLe_yzs: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["putaojiu_yzs", "caisedebai_yzs", "dengliangdeguang_yzs", "weixiaochengjiu_yzs"],
		names: "APPLe",
		img: "extension/一中杀/image/APPLe_yzs.png",
		DamageAudio: 1,
		RE_Mystic: [3,[ "dengliangdeguang_yzs","caisedebai_yzs"]],
		RE_AP: 3,
		RE_FC: [6,`你与所有人物同时拼点：若你赢，对其造成1点伤害。无论如何所有人物依次摸1张牌`]
	},

	LegolaShuang_yzs: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["youzou_yzs", "lvlin_yzs"],
		names: "莱戈拉爽",
		img: "extension/一中杀/image/LegolaShuang_yzs.png",
	},

	Aura_yzs: {
		sex: "female",
		group: "wu",
		hp: 4,
		skills: ["tianping_yzs", "Auserlese_yzs"],
		names: "阿乌拉",
		img: "extension/一中杀/image/Aura_yzs.png",
	},

	Marcus_yzs: {
		sex: "female",
		group: "wei",
		hp: 4,
		skills: ["fanyueciye_yzs", "jingduke_yzs", "yudenghuozhong_yzs", "huiwanggengyuanchu_yzs"],
		names: "马库斯",
		img: "extension/一中杀/image/Marcus_yzs.png",
		DamageAudio: 2,
		RE_Mystic: [4, ["jingduke_yzs", "yudenghuozhong_yzs"]],
		RE_AP: 2,
		RE_FC: [8, `将你所有神秘术升1阶，每有1张不可升阶则你分配1点伤害`]
	},

	Reze_yzs: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["fuse_yzs"],
		names: "蕾赛",
		img: "extension/一中杀/image/Reze_yzs.png",
		dieAudios: ["ext:一中杀/audio/die/Reze_yzs.mp3"],
	},

	Cayuu_yzs: {
		sex: "female",
		group: "wei",
		hp: 1,
		maxHp:5,
		skills: ["longzhiban_yzs","shitianlongjian_yzs","longzhiwu_yzs"],
		names: "加羽",
		img: "extension/一中杀/image/Cayuu_yzs.png",
		DamageAudio: 1,
		dieAudios: ["ext:一中杀/audio/die/Cayuu_yzs.mp3"],
	},

	MrDragon_yzs: {
		sex: "male",
		group: "wei",
		hp:4,
		skills: ["longzhiban_yzs_MrDragon_yzs"],
		names: "龙先生",
		img: "extension/一中杀/image/MrDragon_yzs.png",
		isUnseen: true,
		dieAudios: ["ext:一中杀/audio/die/MrDragon_yzs.mp3"],
	},

	Ren_yzs: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["shuhuenci_yzs", "bianzangsong_yzs", "dapiwansi_yzs"],
		names: "刃",
		img: "extension/一中杀/image/Ren_yzs.png",
	},

	Linie_yzs: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["AirFazen_yzs", "xuanzhan_yzs", "huanwu_yzs"],
		names: "莉涅",
		img: "extension/一中杀/image/Linie_yzs.png",
	},

	Alastor_yzs: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp:4,
		skills: ["guangbo_yzs", "CrimsonShadow_yzs", "GuiltyDemon_yzs"],
		names: "阿拉斯托",
		img: "extension/一中杀/image/Alastor_yzs.png",
		BGM: "Insane",
	},

	jianSheng_yzs: {
		sex: "male",
		group: "shu",
		hp: 1,
		skills: ["jiansheng_yzs", "jiahu_yzs"],
		names: "李砺心",
		img: "extension/一中杀/image/jianSheng_yzs.png",
		DamageAudio: 2,
		dieAudios: ["ext:一中杀/audio/die/jianSheng_yzs.mp3"],
	},

	RenEmperor_yzs: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["shengyu_yzs", "yuanzheng_yzs", "caijue_yzs", "tongshe_yzs"],
		names: "瑞辰",
		img: "extension/一中杀/image/RenEmperor_yzs.png",
	},

	TimeGuard_yzs: {
		sex: "female",
		group: "wei",
		hp: 4,
		skills: ["Calibration_yzs", "TimeBomb_yzs", "TimeMachine_yzs"],
		names: "咲延",
		img: "extension/一中杀/image/TimeGuard_yzs.png",
	},

	LoverW_yzs: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["AiMu_yzs", "AiSi_yzs"],
		names: "W²",
		img: "extension/一中杀/image/LoverW_yzs.png",
	},

	Frieren_yzs: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["tonglv_yzs", "cangfa_yzs","tanbao_yzs"],
		names: "芙莉莲",
		img: "extension/一中杀/image/Frieren_yzs.png",
		BGM: "勇者",
	},

	Himmel_yzs: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["zhenglv_yzs", "zhuxiang_yzs", "yongyi_yzs"],
		names: "辛美尔",
		img: "extension/一中杀/image/Himmel_yzs.png",
		dieAudios: ["ext:一中杀/audio/die/Himmel_yzs.mp3"],
		BGM: "勇者",
	},

	Youmu_yzs: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["guangyousheguainiao_yzs", "liugenqingjingzhan_yzs"],
		names: "魂魄妖梦",
		img: "extension/一中杀/image/Youmu_yzs.png",
		Fuka: 6,
		BGM: "メグルユメ",
	},

	Frisk_yzs: {
		sex: "female",
		group: "qun",
		hp: 4,
		skills: ["shane_yzs", "yuduo_yzs"],
		names: "福里斯克",
		img: "extension/一中杀/image/Frisk_yzs.png",
		DamageAudio: 1,
		dieAudios: ["ext:一中杀/audio/die/Frisk_yzs.mp3"],
	},

	ChengGuixiang_yzs: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["yanjiao_yzs", "choubei_yzs"],
		names: "成鬼香",
		img: "extension/一中杀/image/ChengGuixiang_yzs.png",
	},

	OnionMan_yzs: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["OnionCells_yzs", "Quirk_yzs","Absurd_yzs"],
		names: "任瑞",
		img: "extension/一中杀/image/OnionMan_yzs.png",
	},

	OnionMan_yzs2: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: [ "Quirk_yzs", "Absurd_yzs"],
		names: "任瑞",
		img: "extension/一中杀/image/OnionMan_yzs.png",
		isUnseen: true,
	},

	Byakuren_yzs: {
		sex: "female",
		group: "shu",
		hp: 5,
		skills: ["chaoren_yzs", "youxingsheng_yzs"],
		names: "圣白莲",
		img: "extension/一中杀/image/Byakuren_yzs.png",
	},

	Okina_yzs: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["ReverseInvoker_yzs", "houhukuangyan_yzs"],
		names: "摩多罗隐歧奈",
		img: "extension/一中杀/image/Okina_yzs.png",
	},

	Yan_yzs: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["CityWill_yzs", "FreeWill_yzs", "LiberationTide_yzs"],
		names: "阳 比斯莫克",
		img: "extension/一中杀/image/Yan_yzs.png",
		BGM: "Children of the City",
	},

	Riko_yzs: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["MadeInAbyss_yzs"],
		names: "莉可",
		img: "extension/一中杀/image/Riko_yzs.png",
		BGM: "かたち",
	},

	Reg_yzs: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["huozangpao_yzs","lianhuan_yzs"],
		names: "雷古",
		img: "extension/一中杀/image/Reg_yzs.png",
		BGM: "Deep in Abyss",
	},

	Mamizou_yzs: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["danmubianhua_yzs", "niaoshouxihua_yzs", "manyuefuwu_yzs"],
		names: "二岩猯藏",
		img: "extension/一中杀/image/Mamizou_yzs.png",
		Fuka: 3,
	},

	AomanSzy_yzs: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["aoman_yzs", "jisu_yzs"],
		names: "颂终弈",
		img: "extension/一中杀/image/AomanSzy_yzs.png",
		dieAudios: ["ext:一中杀/audio/die/AomanSzy_yzs.mp3"],
	},

	SCP096_yzs: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["kuangbao_yzs"],
		names: "羞涩的人",
		img: "extension/一中杀/image/SCP096_yzs.png",
		hasHiddenSkill: true,
		isSCP: true,
		BGM: "生存的终焉之光",
	},

	SCP173_yzs: {
		sex: "none",
		group: "qun",
		hp: 4,
		skills: ["haiyi_yzs"],
		names: "雕像",
		img: "extension/一中杀/image/SCP173_yzs.png",
		hasHiddenSkill: true,
		isSCP: true,
		BGM: "生存的终焉之光",
	},

	SCP079_yzs: {
		sex: "none",
		group: "qun",
		hp: 4,
		skills: ["jianshi_yzs"],
		names: "旧AI",
		img: "extension/一中杀/image/SCP079_yzs.png",
		hasHiddenSkill: true,
		isSCP: true,
		BGM: "生存的终焉之光",
	},

	SCP049_yzs: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["chuyi_yzs"],
		names: "疫医",
		img: "extension/一中杀/image/SCP049_yzs.png",
		hasHiddenSkill: true,
		isSCP: true,
		BGM: "生存的终焉之光",
	},

	SCP106_yzs: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["fuqu_yzs"],
		names: "老人",
		img: "extension/一中杀/image/SCP106_yzs.png",
		hasHiddenSkill: true,
		isSCP: true,
		BGM: "生存的终焉之光",
	},

	LightCB_yzs: {
		sex: "none",
		group: "qun",
		hp: 4,
		skills: ["LightContainmentBreak_yzs"],
		names: "轻度收容失效",
		img: "extension/一中杀/image/LightCB_yzs.png",
		BGM: "生存的终焉之光",
	},

	LiTong_yzs: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["zhuofu_yzs","fuli_yzs","yifu_yzs","huanfu_yzs"],
		names: "黎瞳",
		img: "extension/一中杀/image/LiTong_yzs.png",
	},

	BoFengShuiKun_yzs: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["luoxuanwan_yzs", "feileishen_yzs"],
		names: "波风水坤",
		img: "extension/一中杀/image/BoFengShuiKun_yzs.png",
	},

	DarkKnight_yzs: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["yeya_yzs", "anmo_yzs", "pipan_yzs"],
		names: "车肢解",
		img: "extension/一中杀/image/DarkKnight_yzs.png",
		dieAudios: ["ext:一中杀/audio/die/DarkKnight_yzs.mp3"],
	},

	Nanachi_yzs: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["yinju_yzs", "mixiang_yzs", "jingjue_yzs", "shuyu_yzs"],
		names: "娜娜奇",
		img: "extension/一中杀/image/Nanachi_yzs.png",
		BGM: "Deep in Abyss",
	},

	FengCthulhu_yzs: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["Sacrifice_yzs", "ReligiousOrder_yzs"],
		names: "冯 吉苏克",
		img: "extension/一中杀/image/FengCthulhu_yzs.png",
	},

	tentacle_yzs: {
		sex: "none",
		group: "qun",
		hp: 1,
		skills: ["AbyssServant_yzs"],
		names: "深渊之触",
		img: "extension/一中杀/image/tentacle_yzs.png",
		isUnseen: true,
	},

	Keiki_yzs: {
		sex: "female",
		group: "wei",
		hp: 5,
		skills: ["zaoxingshu_yzs"],
		names: "埴安神袿姬",
		img: "extension/一中杀/image/Keiki_yzs.png",
	},

	Yugi_yzs: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["dajiangshanlan_yzs", "sanbubisha_yzs", "guiqikuanglan_yzs"],
		names: "星熊勇仪",
		img: "extension/一中杀/image/Yugi_yzs.png",
		BGM: "神々が恋した幻想郷",
	},

	Reimu_yzs: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["dajiejie_yzs", "erchongjiejie_yzs", "yinyangyu_yzs", "mengxiangfengyin_yzs"],
		names: "博丽灵梦",
		img: "extension/一中杀/image/Reimu_yzs.png",
		Fuka: 3,
		BGM: "神々が恋した幻想郷", 
	},

	Reimu_yzs_Barrier_yzs: {
		sex: "none",
		group: "shu",
		hp: Infinity,
		skills: ["Reimu_yzs_Barrier_yzs_skill"],
		names: "结界",
		img: "extension/一中杀/image/Reimu_yzs_Barrier_yzs.png",
		isUnseen:true,
	},

	Reimu_yzs_subBarrier_yzs: {
		sex: "none",
		group: "shu",
		hp: 1,
		skills: ["Reimu_yzs_subBarrier_yzs_skill"],
		names: "子结界",
		img: "extension/一中杀/image/Reimu_yzs_subBarrier_yzs.png",
		isUnseen: true,
	},

	WaiJiaoDaChen_yzs: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["pingpongWaiJiao_yzs","huhua_yzs"],
		names: "车杳",
		img: "extension/一中杀/image/WaiJiaoDaChen_yzs.png",
	},

	Mokou_yzs: {
		sex: "female",
		group: "shu",
		hp: 1,
		maxHp: 6,
		skills: ["PhoenixLegend_yzs", "HumanBuring_yzs"],
		names: "藤原妹红",
		img: "extension/一中杀/image/Mokou_yzs.png",
		Fuka: 1,
		BGM: "泡沫、哀のまほろば", 
	},

	DoremySweet_yzs: {
		sex: "female",
		group: "wei",
		hp:4,
		skills: ["DreamCatcher_yzs", "DreamInMe_yzs"],
		names: "哆来咪 苏伊特",
		img: "extension/一中杀/image/DoremySweet_yzs.png",
	},

	Reisen_yzs: {
		sex: "female",
		group: "qun",
		hp: 4,
		skills: ["DisorderEye_yzs", "VisionaryTuning_yzs", "LunaticRedEyes_yzs", "InvisibleFullMoon_yzs"],
		names: "铃仙",
		img: "extension/一中杀/image/Reisen_yzs.png",
		Fuka: 3,
		BGM: "泡沫、哀のまほろば",
	},

	BaiLu_yzs: {
		sex: "female",
		group: "wei",
		hp: 4,
		skills: ["xuanhujishi_yzs", "wangwenwenqie_yzs", "shijiebuju_yzs"],
		names: "白露",
		img: "extension/一中杀/image/BaiLu_yzs.png",
	},

	DaZuo_yzs: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["kending_yzs", "bianzhuang_yzs", "juanKill_yzs"],
		names: "鲁日立",
		img: "extension/一中杀/image/DaZuo_yzs.png",
	},

	ChenJiahao_yzs: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["gaoluan_yzs", "xintaibaozha_yzs", "nongdiu_yzs"],
		names: "陈家豪",
		img: "extension/一中杀/image/ChenJiahao_yzs.png",
	},

	ChenDao_yzs: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["ShakingSpirit_yzs", "GodgivenSwordsmanship_yzs", "MandateAura_yzs", "xiangjian_yzs", "jianzhi_yzs", "WindSword_yzs", "CloudSword_yzs", "ThunderWithMe_yzs"],
		names: "陈刀",
		img: "extension/一中杀/image/ChenDao_yzs.png",
	},

	Stark_yzs:{
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jianren_yzs", "shantianji_yzs", "qieyong_yzs"],
		names: "休塔尔克",
		img: "extension/一中杀/image/Stark_yzs.png",
	},

	BDCheTianke_yzs: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["BladeDemon_yzs", "BloodFeast_yzs", "BloodCovenant_yzs"],
		names: "车天可",
		img: "extension/一中杀/image/BDCheTianke_yzs.png",
	},

	BDXiangSiniao_yzs: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["DemonBlade_yzs", "BloodFeast_yzs"],
		names: "向思尼奥",
		img: "extension/一中杀/image/BDXiangSiniao_yzs.png",
		isUnseen:true,
	},

	VanXiongFeng_yzs: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["ExFighting_yzs", "BruteForceArmament_yzs"],
		names: "范熊封次郎",
		img: "extension/一中杀/image/VanXiongFeng_yzs.png",
	},

	HaiWeier_yzs: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["canhuozhong_yzs", "xingnujingyan_yzs","LavaShell_yzs"],
		names: "海威尔",
		img: "extension/一中杀/image/HaiWeier_yzs.png",
	},

	VanXiongYong_yzs: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["bili_yzs", "congling_yzs"],
		names: "范熊勇太郎",
		img: "extension/一中杀/image/VanXiongYong_yzs.png",
		DamageAudio: 1,
	},

	YanLaFeng_yzs: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["wenyanxuci_yzs", "chongshi_yzs"],
		names: "言辣奉",
		img: "extension/一中杀/image/YanLaFeng_yzs.png",
	},

	Serie_yzs: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["wanfa_yzs", "kanpo_yzs", "jiejie_yzs"],
		names: "赛丽艾",
		img: "extension/一中杀/image/Serie_yzs.png",
	},

	Macht_yzs: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dianjin_yzs", "Deeagorze_yzs"],
		names: "马哈特",
		img: "extension/一中杀/image/Macht_yzs.png",
	},

	LeiChenjing_yzs: {
		sex: "female",
		group: "wu",
		hp: 4,
		skills: ["chaodaoti_yzs", "jingdianmabi_yzs"],
		names: "雷辰静",
		img: "extension/一中杀/image/LeiChenjing_yzs.png",
	},

	FoolSeele_Vollerei_yzs: {
		sex: "female",
		group: "shen",
		hp: 1,
		skills: ["Foolshuangsheng_yzs", "Foolchuangsheng_yzs", "Foolxieshengzhijing_yzs", "Foolniworuyi_yzs"],
		names: "希儿",
		img: "extension/一中杀/image/Seele_Vollerei_yzs.png",
	},

	LilyCommie_yzs: {
		sex: "female",
		group: "qun",
		hp: 4,
		skills: ["InvisibleHand_yzs", "FreeMarket_yzs", "AnchoringEffect_yzs", "ReminderNotice_yzs", "PonziScheme_yzs", "FinancialWaltz_yzs"],
		names: "莉莉 康米",
		img: "extension/一中杀/image/LilyCommie_yzs.png",
		BGM: "今宵は飄逸なエゴイスト",
	},

	SCP939_yzs: {
		sex: "none",
		group: "qun",
		hp: 4,
		skills: ["qiehou_yzs", "xunsheng_yzs","qianfu_yzs"],
		names: "千喉之兽",
		img: "extension/一中杀/image/SCP939_yzs.png",
		hasHiddenSkill: true,
		isSCP: true,
		BGM: "生存的终焉之光",
	},

	DomenicoPucci_yzs: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["WeatherReport_yzs", "StormRain_yzs"],
		names: "多明尼克 普奇",
		img: "extension/一中杀/image/DomenicoPucci_yzs.png",
	},

	ReiujiUtsuho_yzs: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["NuclearHeat_yzs", "Tokamak_yzs","SubterraneanSun_yzs"],
		names: "灵乌路空",
		img: "extension/一中杀/image/ReiujiUtsuho_yzs.png",
		BGM: "灵知的太阳信仰 ～ Nuclear Fusion",
	},

	Rafau_yzs: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["guanxing_yzs", "chushi_yzs", "cesuan_yzs"],
		names: "拉法尔",
		img: "extension/一中杀/image/Rafau_yzs.png",
		BGM: "怪獣1",
	},

	Getian_yzs: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["shigu_yzs", "lingleidegu_yzs", "duyidexiang_yzs", "wosiguwozai_yzs"],
		names: "葛天",
		img: "extension/一中杀/image/Getian_yzs.png",
		DamageAudio: 2,
		RE_Mystic: [3, ["lingleidegu_yzs", "duyidexiang_yzs"]],
		RE_AP: 3,
		RE_FC: [5, `若当前不为【谶语风暴】，你召引之并获得：<br>吟唱5：失去本吟唱并终止之。场上角色受到伤害时，本吟唱-1。【谶语风暴】结束时，失去本吟唱并获得剩余吟唱数点激情；否则将上述吟唱变为5，并令【骨相】角色调整1点体力。`]
	},

	KinMiho_yzs: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["KingsTrove_yzs", "zhengling_yzs"],
		names: "坷垃金 米霍",
		img: "extension/一中杀/image/KinMiho_yzs.png",
	},

	KaalaBaauna_yzs: {
		sex: "female",
		group: "wei",
		hp: 4,
		skills: ["yixingzhixue_yzs","tishuyinyong_yzs", "gufaguanxing_yzs","duyideyuanman_yzs"],
		names: "伽菈波那",
		img: "extension/一中杀/image/KaalaBaauna_yzs.png",
		DamageAudio: 2,
		dieAudios: ["ext:一中杀/audio/die/KaalaBaauna_yzs.mp3"],
		RE_Mystic: [5, ["tishuyinyong_yzs", "gufaguanxing_yzs"]],
		RE_AP: 3,
		RE_FC: [function(player){ return `X(${player.countMark("duyideyuanman_yzs") + 1})` }, `若X为5，移去“星环”内全部牌，本次结算中移去行星牌效果数字+1，结算后获得2张【盈月】并重置X为1；否则获得1张【盈月】。`]
	},

	Arlecchino_yzs: {
		sex: "female",
		group: "shu",
		hp: 2,
		skills: ["sishengzhijian_yzs", "chijingzhiyi_yzs", "yuhuozhige_yzs"],
		names: "阿蕾奇诺",
		img: "extension/一中杀/image/Arlecchino_yzs.png",
	},

	MegumiSukuna_yzs: {
		sex: "male",
		group: "shu",
		hp: 30,
		skills: ["zuzhouzhiwang_yzs", "shizhongyingfashu_yzs", "fanzhuanshushi_yzs","jie_yzs","ba_yzs","fumoyuchuzi_yzs"],
		names: "宿傩(伏黑惠)",
		img: "extension/一中杀/image/MegumiSukuna_yzs.png",
		BGM: "Malevolent Shrine",
	},

	Makora_yzs: {
		sex: "male",
		group: "qun",
		hp: 6,
		skills: ["hundunyutiaohe_yzs", "tuimozhijian_yzs"],
		names: "魔虚罗",
		img: "extension/一中杀/image/Makora_yzs.png",
		BGM: "Malevolent Shrine",
		isUnseen: true,
	},

	RyomenSukuna_yzs: {
		sex: "male",
		group: "shu",
		hp: 30,
		skills: ["zuzhouzhiwang_yzs", "liangmianguishen_yzs", "fanzhuanshushi_yzs", "jie_yzs", "ba_yzs", "fumoyuchuzi_yzs"],
		names: "两面宿傩",
		img: "extension/一中杀/image/RyomenSukuna_yzs.png",
		BGM: "Malevolent Shrine",
	//	isUnseen: true,
	},

	GojoSatoru_yzs: {
		sex: "male",
		group: "wei",
		hp: 10,
		skills: ["SixEyes_yzs", "wuxiaxianshushi_yzs", "xushici_yzs", "fanzhuanshushi_yzs", "wuliangkongchu_yzs"],
		names: "五条悟",
		img: "extension/一中杀/image/GojoSatoru_yzs.png",
		BGM: "AIZO",
	//	isUnseen: true,
	},

	Sakuya_yzs: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["TheWorld_yzs", "KillingDoll_yzs"],
		names: "十六夜咲夜",
		img: "extension/一中杀/image/Sakuya_yzs.png",
		Fuka: 3,
	},

	ZeninMaki_yzs: {
		sex: "female",
		group: "wu",
		hp: 3,
		hujia:3,
		skills: ["shuangzizhoufu_yzs", "tianyubaojun_yzs"],
		names: "禅院真希",
		img: "extension/一中杀/image/ZeninMaki_yzs.png",
		BGM: "AIZO",
	},

	ZeninNaoya_yzs: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["huizhen_yzs", "toushezhoufa_yzs"],
		names: "禅院直哉",
		img: "extension/一中杀/image/ZeninNaoya_yzs.png",
		BGM: "AIZO",
		dieAudios: ["ext:一中杀/audio/die/ZeninNaoya_yzs.mp3"],
	}
};

const characterSubstitutes = {
};
const characterTitles = {
	YouBeier_yzs: "近乎无所不切的魔法",
	LU_Captain_xiangsiniao_yzs:"奖励队长",
	HuangJOJO_yzs:"黄JOJO",
	JiLiangJiTao_yzs:"平凡上学族",
	shenChangzhang_yzs:"血腥屠夫",
	shenfu_Limu_yzs:"神父",
	WZZS_lilixin_yzs: "歪嘴战神",
	changzhang_yzs:"厂长",
	jealous_witch_yzs:"嫉妒魔女",
	lianhua_yzs: "理与迷宫的少女",
	hunziKing_yzs: "混子王",
	wuyingYFY_yzs: "无影之勇者",
	Cana_yzs: "女武神",
	Lazy_twins_yzs: "怠惰双子",
	Remilia_Scarlet_yzs: "幼小的红月",
	chenxu_yzs: "不灭的鲛人",
	AngryFeng_yzs: "暴怒刀皇",
	Unbelieve_xiangzi_yzs: "全然不信",
	yagamiLight_yzs: "新世界的神",
	Halo_yzs: "精灵公主",
	Noir_yzs: "正义执行",
	lianjinzhencai_yzs: "炼金术士",
	weaponmaster_yzs: "武器大师",
	SukunaShinmyoumaru_yzs: "小人族的末裔",
	Cirno_yzs: "冰之小妖精",
	Patchouli_Knowledge_yzs: "七曜の魔法使",
	Yorigami_twins_yzs: "最凶最恶的双子姐妹",
	Ibuki_Suika_yzs: "娇小的百鬼夜行",
	Zbro_yzs: "频凡世界",
	toothFairy_yzs: "予你甜梦",
	RatTiger_yzs: "宝物二人组",
	Floris_yzs: "001",
	ChainsawCock_yzs: "电锯鸡",
	Chino_yzs: "亡国的吸血姬",
	Seele_Vollerei_yzs: "死生之律者",
	Qianmian_Limu_yzs: "千面勇者",
	Fern_yzs: "瞬击的魔法使",
	Marisa_yzs: "普通的魔法使",
	Tenshi_yzs: "非想非非想天之女",
	Onozuka_Komachi_yzs: "黄泉摆渡人",
	NatsukiSubaru_yzs: "从零开始的穿越者",
	EastYang_yzs: "国王之手",
	Denglanxitaro_yzs: "狂妄之狼",
	Zhonghuang_yzs: "不弑之勇者",
	Xiangbolin_yzs: "调香师",
	PhantomEnsemble_yzs:"幽灵乐团",
	cunhe_yzs: "反叛的海贼",
	Yuyuko_yzs: "华胥的亡灵",
	tangjiheChao_yzs: "无畏之勇者",
	LilyWhite_yzs: "运送春天的妖精",
	AdmiredWitch_yzs: "神倾魔女",
	IceGirl_yzs: "冰女",
	Innocent_xiangzi_yzs: "真之勇者",
	TimeThief_yzs: "时潜怪盗",
	Patriot_yzs: "爱国者",
	DreamWitch_yzs: "崎梦魔女",
	DimensionWitch_yzs: "次元魔女",
	SixSoulsFlowey_yzs: `<span class="yzs_xuancai">地下世界的伪神</span>`,
	FailedFlowey_yzs: "一朵名叫小花的花",
	QiGongMaster_yzs: "气功大师",
	yinBochen_yzs: "二次元之王",
	Akyuu_yzs: "幻想乡的记忆",
	APPLe_yzs: "光往何处去",
	LegolaShuang_yzs: "精灵游侠",
	Aura_yzs: "断头台",
	Marcus_yzs: "灯塔集",
	Reze_yzs: "炸弹恶魔",
	Cayuu_yzs: "年幼的龙骑士",
	Ren_yzs: "逐死的猎手",
	Linie_yzs: "模仿魔法",
	Alastor_yzs: "广播恶魔",
	jianSheng_yzs: "清廉剑圣",
	RenEmperor_yzs: "人皇",
	TimeGuard_yzs: "时间守护者",
	LoverW_yzs: "恋人",
	Frieren_yzs: `最后的大魔法使`,
	Himmel_yzs: `真正的勇者`,
	Youmu_yzs: `幽人的庭师`,
	Frisk_yzs: `一念殊途`,
	ChengGuixiang_yzs: `死亡抽背`,
	OnionMan_yzs: `洋葱怪人`,
	OnionMan_yzs2: `洋葱怪人`,
	Byakuren_yzs: `勇往直前僧侣`,
	Okina_yzs: `究极的绝对秘神`,
	Yan_yzs: `都市的传令员`,
	Riko_yzs: `奈落的旅人`,
	Reg_yzs: `奈落至宝`,
	Mamizou_yzs: `狸猫十变化`,
	AomanSzy_yzs: `傲慢魔神`,
	SCP096_yzs: `SCP-096`,
	SCP173_yzs: `SCP-173`,
	SCP079_yzs: `SCP-079`,
	SCP049_yzs: `SCP-049`,
	SCP106_yzs: `SCP-106`,
	LiTong_yzs: `天符国师`,
	BoFengShuiKun_yzs: `火坤忍者`,
	DarkKnight_yzs: `黑暗骑士`,
	Nanachi_yzs:`奈落布偶`,
	FengCthulhu_yzs: `异界使者`,
	Keiki_yzs: `造物的神明`,
	Yugi_yzs: `旧地狱的鬼王`,
	Reimu_yzs: `乐园的巫女`,
	WaiJiaoDaChen_yzs: `外交大臣`,
	Mokou_yzs: `蓬莱的人之形`,
	DoremySweet_yzs: `支配梦境之貘`,
	Reisen_yzs: `狂气的月兔`,
	BaiLu_yzs: `衔药龙女`,
	DaZuo_yzs: `大佐`,
	ChenJiahao_yzs: `空气高中牲`,
	ChenDao_yzs:`天命之勇者`,
	Stark_yzs: `胆小的屠龙者`,
	BDCheTianke_yzs: `嗜血剑魔`,
	BDXiangSiniao_yzs: `嗜血魔剑`,
	VanXiongFeng_yzs: `狂蛮之勇者`,
	HaiWeier_yzs: `红魔龙`,
	VanXiongYong_yzs: `驯兽之勇者`,
	YanLaFeng_yzs: `文言歌者`,
	Serie_yzs: `神话中的大魔法使`,
	LeiChenjing_yzs: `雷之勇者`,
	FoolSeele_Vollerei_yzs: `死生之律者`,
	LilyCommie_yzs: `贪欲`,
	SCP939_yzs: `SCP-939`,
	DomenicoPucci_yzs: `加速世界的乌云`,
	ReiujiUtsuho_yzs: `炽热难驭的神之火`,
	Rafau_yzs: `追寻合理之美`,
	Getian_yzs: `山中来客`,
	KinMiho_yzs: `双面国王`,
	KaalaBaauna_yzs: `晚星所纺织的`,
	Arlecchino_yzs: `仆人`,
	MegumiSukuna_yzs: `史上最强咒术师`,
	Makora_yzs:`八握剑 异戒神将`,
	RyomenSukuna_yzs: `史上最强咒术师`,
	GojoSatoru_yzs: `现代最强咒术师`,
	Sakuya_yzs: `优雅而潇洒的从者`,
	ZeninMaki_yzs: `缚咒的凶雁`,
	ZeninNaoya_yzs:`名门的妄执`,
};
const characterIntros = {
	Enrico_Pucci_yzs: `恩里克·普奇，通称“普奇神父”，漫画《JOJO的奇妙冒险：石之海》及其衍生作品中的反派角色。他是前作的大BOSS，乔斯达家族的宿敌——迪奥·布兰度的挚友。与迪奥一同追求名为“天堂”的存在。普奇担任绿海豚街监狱的教诲师，对神学有充分的了解与研究。在迪奥被远征埃及的星尘十字军杀死后，普奇继承了他的理想，致力于实现迪奥所描绘过的“天堂”。为了得到到达天堂的方法，他设计陷害了空条徐伦，使其被判刑进入绿海豚街监狱，以此为诱饵迫使空条承太郎现身并夺取其记忆，引发了《石之海》的故事。`,
	YouBeier_yzs: `三级魔法使，身着黑色连衣裙的少女。前往魔法都市奥伊萨斯特参加一级魔法使考试的考生之一，也是最终合格的六名考生之一。性格十分恶劣，喜欢说话，喜欢战斗，也喜欢缠着自己感兴趣的人。不太会主动动手杀人，但对于杀人也一度毫不抗拒；因性格和事迹而被认定是“问题儿童”“杀掉比较好的人”。拥有相当的魔法才能和战斗直觉，还拥有异于常人的精神力。掌握的魔法大都非常唯心，是“魔法的世界就是想象的世界”这一设定的最直接体现者之一。有一个做裁缝的姐姐。和菲伦、兰托在第一轮考试中被分在一组，在团队中承担活跃气氛和被兰托吐槽的工作。运气很差，又很笨拙，还会莫名其妙地害羞。名字源于德语，意为“恶劣的”。极少数名字是负面词汇的人类之一。`,
	jealous_witch_yzs: "“W，你为何会变成这样？”——陈刀<br>“陈刀哥哥，从死亡中归来后，我明白了——我们的爱，即使死了——不，只有死了才能延续下去！”",
	lianhua_yzs: `莲华（れんげ），游戏《美少女万华镜》及其衍生作品中的角色之一，由真中海配音。莲华，深见夏彦的引路人，居住在深山某旅店的人偶之屋中，并自称是房间的主人。虽然看上去是个小女孩，但是却有着非同一般的气场。给人以冷漠印象，有点毒舌。拥有能窥视普通人类所窥视不到的世界的奇妙万华镜`,
	Remilia_Scarlet_yzs:`蕾米莉亚·斯卡蕾特，系列作品《东方Project》中的角色，于《东方红魔乡》作为六面BOSS首次登场。她是居住在红魔馆的吸血鬼，是红魔馆的主人，拥有操纵命运程度的能力。虽然年龄有500岁，但是性格像小孩子一样幼稚任性，而且非常高傲。吸血鬼异变和红雾异变的发起者，在东方红魔乡中作为最终BOSS被击败后于东方萃梦想中首次成为自机角色。`,
	wuyingYFY_yzs: "......",
	Cana_yzs:`“那把枪与刃不是我对你的同情，而是我对你的欣赏。”<br>“翔子，当你读到这时我应该已经死了，不要为我悲伤。还有，要做一个永远的少年哦。”`,
	Lazy_twins_yzs:`“嗯？要跟咱战斗吗？好麻烦啊...”   ——冬<br>“可别小瞧了咱，咱以前可姑且算是魔女来着...话说你俩看着有点眼熟呢~”——祺`,
	chenxu_yzs: `杀死我同胞的家伙们！我，嗔嘘，会将你们彻底击垮！`,
	AngryFeng_yzs: `“曾经受人们敬仰的刀皇，因千面的谣言与诡计遭到人们的侮辱，友人的怀疑，内心正直的他因此暴怒，遁入魔道。人类啊，真是有趣！”——傲慢`,
	Unbelieve_xiangzi_yzs: `“若你再向陈刀他们踏出一步，你将迎来噩梦。”<br>“李暮！像你这样的勇者，就该在地狱里焚烧！”`,
	yagamiLight_yzs: `“我将成为神，制裁这个世界，代表正义。”<br><br>夜神月（やがみライト）是日本动漫《死亡笔记》及其衍生作品中的主角，第二代L，被信徒称为kira，他智力超群、体育全能、心理素质极强，是近乎变态的完美主义者，认为世界正在腐朽，希望创造一个没有犯罪的新世界`,
	Halo_yzs: `“身为圣女候补兼公主，虽然难说能做得跟钟姐姐一样好，但我会努力的！”<br>“阿爽，今后也拜托你了。”`,
	lianjinzhencai_yzs: `“陛下，我为您献上我的毕生杰作—【也太】，这种奇药能极大增强您士兵的力量！陛下，只需再得到鲛人鳍，它便能实现量产！”<br>“陛下，一只鲛人闯入了研究所，两名实验体逃脱，请陛下派出陈序追捕。”<br>“鹏程师傅，我现在做的，真的是正确的吗？”`,
	weaponmaster_yzs: `想学剑技啊？那简单——先把学费交一下。”——车杳  <br>“少主，您的兄长还是下落不明，如今还请谨慎行事！” ——翼飞羽`,
	SukunaShinmyoumaru_yzs: `少名针妙丸是日本同人游戏《东方Project》系列中的虚拟角色，首次作为六面BOSS登场于《东方辉针城》，种族为小人族一寸法师的末裔，拥有使用万宝槌的能力。该角色原型源于日本民间传说《一寸法师》，身着红色和服并佩戴写有藤蔓纹样的碗状头饰，主题曲为《辉光之针的小人族 ～ Little Princess》。因被天邪鬼正邪伪造历史欺骗，针妙丸挥动万宝槌引发"下克上"异变，导致妖怪力量失控、物品化为付丧神，后被博丽巫女击败并收留在神社监管。在《东方深秘录》事件中为验证灵异珠效果参与争夺，并与比那名居天子在《东方凭依华》中组队形成战斗组合。异变结束后暂时失去体型变化能力。该角色后续活跃于《弹幕天邪鬼》《东方铃奈庵》等衍生作品，性格兼具耿直特质与因种族身份产生的自卑心理，与正邪保持复杂互动关系。其符卡包含"小槌“变大吧”""妖剑“辉针剑”"等特色招式`,
	Cirno_yzs: `琪露诺（チルノ/Cirno）是上海爱丽丝幻乐团开发的《东方Project》系列弹幕游戏中的虚拟角色。冰之妖精。她在《东方红魔乡》中作为2面Boss首次登场，被急着赶去红魔馆的灵梦等人击败。平时她住在位于妖怪之山山麓的雾之湖附近。她拥有能够操纵冷气，将任何事物（有时甚至包含弹幕）冻结的能力。大多数妖精都不是危险的存在，但因为琪露诺有爱找茬的性格，能力带来的冷气也很强，在幻想乡中属于很强的妖精。但是她很强的只有能力，头脑上则很弱。不过凡事不太经过大脑思考是妖精的共通特征。妖精共通的特征还有一点，就是爱捣乱。 [7]在东方花映冢的介绍图中，琪露诺的位置⑨被标注为“バカ”（笨蛋），因此粉丝常用⑨、笨蛋、baka称呼琪露诺`,
	Patchouli_Knowledge_yzs: `帕秋莉·诺蕾姬，系列作品《东方Project》中的角色。魔法使，拥有使用魔法程度的能力，于《东方红魔乡》中作为四面BOSS首次登场。是红魔馆馆主蕾米莉亚的朋友，定居于红魔馆地下图书馆的魔法使`,
	Yorigami_twins_yzs: `依神紫苑是《东方Project》系列中的贫穷神角色，首次登场于格斗游戏《东方凭依华》。作为“最凶最恶双子”中的姐姐，她拥有向一切对象降下不幸的特殊能力，姓名取自春紫苑花，其花语为“追想的爱”，其存在本身即构成被人类畏惧的灾厄象征。性格消极倦怠的她长期依赖妹妹女苑行动，实则通过自身贫穷属性暗中守护他人免遭更大灾祸。因试图凭依他人摆脱困境，反致妹妹陷入同等窘境。紫苑因性质特殊仍居神社，逐渐适应环境并结识天子，性格出现微妙转变。<br>依神女苑是《东方Project》系列弹幕游戏《东方凭依华》初登场的虚拟角色，属于疫病神种族，与姐姐依神紫苑并称“最凶最恶的双子”。其能力为“使人消耗财产”，角色主题曲为《今宵は飘逸なエゴイスト》，姓名源自姬女苑的花语“朴素而清楚”。她性格傲慢且充满支配欲，擅长通过言语操控人类挥霍财产直至破产。在《东方凭依华》事件中，策划让紫苑完全凭依对手以夺取胜算，但被八云紫识破后送往命莲寺修行。修行期间虽短暂反省，最终仍选择逃离寺庙回归自由身。姐妹关系复杂，紫苑作为贫穷神无法积累财富，而她获得财富后即刻挥霍，形成互补且矛盾的双子羁绊。尽管经历事件后试图与过去割裂，但长期扭曲的价值观使其难以彻底改变。对财富的执念与挥霍本性，以及利用与反抗交织的姐妹互动，构成了角色充满张力的命运轨迹。`,
	Ibuki_Suika_yzs: `伊吹萃香是鬼之四天王之一，拥有很大的力气。不知为何会出现在幻想乡，由于幻想乡有相当长的时间没出现过鬼，对于驱鬼的方法已经失传许久，没人会退治鬼，大家都感到为难。因此萃香和其他的鬼才能定居下来。虽然外表是一个小女孩，看上去并不吓人，但她是一只已活了几百年的鬼，拥有将事物集结与分散程度的能力，和让人害怕的怪力。她曾夸下海口，只要她想，就能凭一人之力将妖怪之山推倒。萃香十分喜欢喝酒，常带着一个酒葫芦并喝得醉醺醺的，在东方的三款格斗游戏中，都可以看到她走路是摇摇晃晃的。其原形来自于鬼头目之中的“酒吞童子”。性格豪爽，喜欢酒与宴会，天真而且单纯，喜欢和人一较高下，像是小孩子的性格。其名字“萃香”与“西瓜”的日文发音相同，故昵称为“西瓜”`,
	toothFairy_yzs: `牙仙，本名坎贝尔（Campbell），游戏《重返未来：1999》星属性六星辅助输出型角色，圣洛夫基金会牙医、第一防线学校校医`,
	RatTiger_yzs:`娜兹玲是《东方Project》系列的女性虚拟角色，首次作为第一关BOSS登场于《东方星莲船》。种族为妖鼠，表面身份是寅丸星的使魔，实为毗沙门天派遣的高阶妖怪，拥有驱使野鼠探测物体的能力，擅长寻找财宝但受限于鼠群特性，无法有效探测活物或大型物品。娜兹玲性格高傲却胆小，因毗沙门天作为靠山表现出自大态度，遇险时极易逃跑。居住在无缘冢附近自建小屋以探寻宝藏，鼠群活动常导致农作物受损，但可通过交涉协助寻物。属于命莲寺势力却不信仰其神明，仅在寅丸星召唤时短暂停留。 该角色在《东方星莲船》《东方兽王园》等作品中多次登场，并于第十六回东方系列人气投票角色部门位列第53名<br>寅丸星，系列作品《东方Project》中的角色，妖兽，拥有收集财宝程度的能力，于《东方星莲船》中作为五面BOSS首次登场。在命莲寺中，她是地位仅次于圣白莲的高僧，是毗沙门天的化身，被作为毗沙门天在命莲寺中供奉，追根溯源，她只是普通的妖兽`,
	ChainsawCock_yzs: `“因爆炸失去双亲并被恶魔诱骗的人啊，现在却是位正义的勇者！”        ——圣女<br>“酷鲁多矿场大爆炸事件的受害者正向另一个受害者复仇？真是可笑！”            ——傲慢`,
	Seele_Vollerei_yzs:`希儿·芙乐艾是手机游戏《崩坏3》及其衍生作品中的角色，可可利亚孤儿院收养的孤儿，天生圣痕觉醒者。2012年与布洛妮娅·扎伊切克相识后成为挚友，因X-10实验意外导致身体量子化，坠入量子之海漂流多年。该角色拥有双重人格，表人格性格温和敏感，畏惧暴力；里人格源自前文明纪元死之律者的记忆，性格强势崇尚武力。2014年代替布洛妮娅参与X-10实验时，因身体无法承受圣痕力量导致量子态转化。三年后布洛妮娅进入量子之海救出希儿，但在返程途中遭遇黑潮再次分离。后续与凯文达成交易解除量子之海屏障，最终通过圣痕之力协同作战救回布洛妮娅。经历支配剧场事件后，双重人格达成和解共享“希儿”之名，表里人格可自由切换战斗形态，运用圣痕力量与量子能量协同作战`,
	Qianmian_Limu_yzs: `“两只被神明蛊惑的迷途羔羊啊，一只傲慢地承担起世界之罪，一只孤独地行走在迷失之街，让我来拯救你们，接管一切成为新世界的主宰吧！”`,
	Fern_yzs: `菲伦，日本漫画《葬送的芙莉莲》及其衍生作品中的角色。被海塔抚养长大的战灾孤儿，同时也是芙莉莲的徒弟。菲伦在芙莉莲的教导下成为了一名能够独当一面的魔法使，并与芙莉莲一同旅行。原三级魔法使，后通过考核成为了一级魔法使`,
	Marisa_yzs: `雾雨魔理沙，系列作品《东方Project》中的主人公，在《东方》系列的游戏中均以主角出场，在其他作品中也作为主要角色登场。魔理沙是一个魔法使。身为一个人类却能够驱使强大的魔法，想在和灵梦竞争一般进行着在异变时插手进行妖怪降伏。居住在远离村子的魔法森林，运营着一家名为雾雨魔法店的「万事屋」，但是魔法森林对于普通的人类来说环境过于残酷所以基本上也没什么顾客光顾。因此，她平时也就埋头于魔法研究，或者就是出入博丽神社。一直穿着一身黑衣的理由，好像是因为穿脏了也不显眼，还有就是她觉得身为魔法使就该穿这种样式的衣服。服装虽然十分朴素但是魔法却喜欢使用外表华丽的道具，喜欢使用将光和热、星星等作为中心的重视威力的魔法，有关魔法的效果也只是纯粹地追求破坏力。虽然她的性格稍有扭曲也不过是稍稍跑偏一点而已，魔理沙的性格基本上还是很直爽的。行动一直都给人一种华丽而又爽快的印象，是做任何事都一步一个脚印慢慢积累的努力家类型的人。与奔放而毫无束缚天才型的灵梦对比起来看，魔理沙作为主要能力的魔法也是她通过努力而习得的技能`,
	Tenshi_yzs: `比那名居天子（ひななゐ てんし，Hinanawi Tenshi）是系列作品《东方Project》中的角色，于《东方绯想天》首次登场。比那名居天子，天界不良天人，拥有操纵大地的能力，携绯想之剑与要石，性格娇纵自负，却在幻想乡凭依风潮中找到匹配拍档，展现变幻莫测的战斗风采，以要石与大气层之力，掌控天地，无人能敌`,
	Onozuka_Komachi_yzs: `小野冢小町，系列作品《东方project》中的角色，死神，拥有操纵距离程度的能力，于《东方花映冢》中作为自机角色首次登场。小町是三途河的船夫，她的职责是将死者从此岸（现界）运送到有阎魔等候的彼岸。死神同时也是阎魔的部下，小町就是负责幻想乡的四季映姬·夜摩仙那度的部下。正因如此，她的船上运送的大多是幻想乡的人类以及妖怪。小町喜欢聊天，她的乐趣就是向船上所载的幽灵搭话。然而她有着偶尔会偷懒怠工的习惯，这也成为了「花映冢」一作中令幻想乡挤满幽灵的原因之一。但那时幽灵的数量本身已经大幅超越了平时，所以并不能将责任全部归咎于小町`,
	NatsukiSubaru_yzs: `菜月昴，轻小说《Re：从零开始的异世界生活》及其衍生作品中的男主角。为人正直善良，有着在逆境中边叫苦边抵抗的品格。穿着与异世界格格不入的运动服。经常锻炼，有着良好的体格，从现代日本的便利店买完泡面就莫名其妙穿越到异世界。被“嫉妒魔女”莎缇拉深爱，拥有权能“死亡回归”。喜欢爱蜜莉雅，深信她是自己在异世界的女主角，为了守护爱蜜莉雅的笑容和走向理想的Happy Ending而不断在死亡中轮回。自我定位为“爱蜜莉雅的骑士”，被雷姆定义为自己的“英雄”，将上述两人称为“心中不可撼动的第一位和第二位”。被魔女们称为“贤者的候补”，与加菲尔·汀泽尔并称“守护爱蜜莉雅的双壁”`,
	EastYang_yzs: `“伊斯特愿终身追随王子陛下，报答王子陛下对我的恩情！”“为新王的诞生献礼！吾王万岁！”`,
	Denglanxitaro_yzs: `抱歉欺骗了你，养父，但我已无法遏制我的利爪去完成它复仇的使命了。”`,
	Zhonghuang_yzs: `“这世间的苦难太多，一个人又怎能承担？我的妹妹是如此，你也是如此阿，陈刀——所以，请冷静下来吧。”`,
	Xiangbolin_yzs: `“秘密发货，有求必应，使命必达且保密百分百！因为售方隔夜后就会忘记（所以请在白天订购哦~）——某工会张贴的广告`,
	PhantomEnsemble_yzs: `骚灵三姐妹又称普雷兹姆利巴三姐妹，是《东方Project》系列游戏中的虚拟角色，首次作为四面Boss登场于《东方妖妖梦》，此后在《东方花映冢》《东方心绮楼》等作品中亦有出场，并在《东方凭依华》中出现在太阳花田的演奏舞台。种族为骚灵（Poltergeist），拥有无需肢体即可演奏乐器的能力，职业为幽灵乐团成员，居住于雾之湖附近的废弃洋馆。三姐妹由人类贵族蕾拉·普莉兹姆利巴创造的骚灵，原为普莉兹姆利巴乐团成员，后加入堀莉兹姆利巴乐团。长女露娜萨性格冷静阴沉，擅长小提琴演奏；次女梅露兰魔力强但使用不当，性格开朗且精通小号；三女莉莉卡性格狡猾，负责键盘与打击乐。其演奏通过精神层面的"音之幽灵"影响听众情绪，常受邀为幻想乡宴会表演。三人分别对应弦乐器、管乐器及键盘/打击乐的演奏体系，符卡包含《合葬「Prism Concerto」》等棱镜折射主题弹幕。主题曲《幽灵乐团 ～ Phantom Ensemble》与妖妖梦四面场景相关联，符卡背景乐谱源自爱德华·格里格的《悲歌旋律》`,
	cunhe_yzs: `“故乡的战火与亲人的眼泪领我来到这里，安心点~我会向那新宪法脱帽致敬的，前提是在你这虚伪的王去死之后！”`,
	Yuyuko_yzs: `西行寺幽幽子，系列作品《东方Project》中的角色，华胥的亡灵，冥界白玉楼的西行寺家的大小姐，于《东方妖妖梦》中作为六面BOSS首次登场，她命令园艺师妖梦从幻想乡中收集春天，从而引发了通称“春雪异变”的异变，但最终受到了顺着被夺走的春天的气息而来的巫女等人的惩罚。西行寺幽幽子行事颇为轻浮，甚至给人一种能飘起来的感觉，其做事风格也飘忽不定`,
	tangjiheChao_yzs: `宁可勇敢过头而鲁莽，不要勇敢不足而怯懦！”`,
	LilyWhite_yzs: `莉莉霍瓦特（リリーホワイト）是《东方Project》系列中的妖精角色，首次登场于《东方妖妖梦》作为四面道中BOSS。运送春天的妖精，告知春天已经来临程度的能力，作为妖精危险度并不高，也不好战。在春雪异变事件中，试图向人类传达春天到来却被误认为攻击者。在《东方花映冢》中为了配合地狱裁判长四季映姬而而换成类似法袍的黑衣服出现。东方系列第一个有名字的道中BOSS，ZUN在开发《妖妖梦》时，为回应玩家对关卡中段头目命名的需求，特地为该角色赋予“莉莉”这一名称`,
	AdmiredWitch_yzs: `“我从小就被神明倾眷，也被神明厌恶，我身边的人都会遭遇不幸。崎梦、次元，我们三魔女都是被神明操纵着的人啊。”`,
	Innocent_xiangzi_yzs: `陈刀先生请带上我吧，虽然我很弱小，但我有不得不去做的事情——我要查清她死亡的真相！`,
	TimeThief_yzs: `时潜怪盗是《游戏王》卡组系列之一，初收录于SAST(1007)卡包，TCG版称“Time Thief”，OCG版名“クロノダイバー”，中文译名融合两者含义而定。该系列由暗属性念动力族与机械族怪兽构成，以夺取对手卡作为超量素材为核心战术，设计灵感源自科幻剧《神秘博士》，并与“超元特防队”等系列共享世界观`,
	Patriot_yzs: `博卓卡斯替，代号“爱国者”，游戏《明日方舟》及其衍生作品中的角色。感染者游击队“盾”的指挥官。萨卡兹勇士中古老至极的血脉，最后一位纯血温迪戈，整合运动的脊骨，也是整合运动的指挥官之一。在与罗德岛激战过后，博卓卡斯替发现了阿米娅的秘密，他回想起了古老的预言，最终倒下，死亡停下了他一生的行军`,
	DreamWitch_yzs: `“肖妹妹能把人们的梦与自己的梦连接起来，并且她在梦中保持着另一种人格。有趣的是，肖她利用这个能力一直在帮人们做梦境心理治疗哦。”——神倾魔女`,
	DimensionWitch_yzs: `“我是次元⭐魔女，今年明年都是18岁，特长是18岁，外号是18岁，宝物是18岁，与那俩老巫婆相比的优点是18岁da⭐ze！”`,
	SixSoulsFlowey_yzs: `出自《传说之下》的游戏BOSS，推荐4名以上玩家挑战，技能描述与实际机制不符，需要玩家自行探索攻略方式。`,
	Akyuu_yzs: `稗田阿求是游戏《东方Project》及其衍生作品中的虚拟角色，在书籍《东方求闻史纪》中作为《幻想乡缘起》的作者初次登场。 [5]太安万侣以曾作为舍人侍奉天武天皇的稗田阿礼所背诵的《帝纪》《旧辞》为基础编纂出了史书《古事记》这一故事中的那位稗田阿礼所转生的孩子，会继承其完全记忆能力，将作为“御阿礼之子”成为稗田家各代当家。从初代的阿一数起，阿求是第九代。为了让村落的人类能够安全生活，阿求与前代的“御阿礼之子”们一样，不断编写书籍，将那些引人注目的妖怪的种种情报总结起来。阿求等人编写的书名为《幻想乡缘起》，主要内容是妖怪图鉴、英雄传、危险地区指南等。不知是否受其能力影响，“御阿礼之子”的寿命比其他人类要短，只能活到大概三十岁。据说在此代逝世后，直到下一次转生的这段时间，“御阿礼之子”都在地狱等待下一具身体准备就绪。因此《幻想乡缘起》基本是每一百二十年到一百八十年左右编写一册`,
	APPLe_yzs: `APPLe，游戏《重返未来：1999》中的角色，星属性四星角色，非人神秘学家，星锑的搭档，博学多才、风度翩翩、幽默风趣、喜欢喝酒`,
	LegolaShuang_yzs: `“前翻滚，追云箭；左翻滚，破魔箭；右翻滚，惊雷箭；后翻滚，吃我一箭！公主——你看到了吗——我的箭技——”`,
	Aura_yzs: `阿乌拉，日本漫画《葬送的芙莉莲》及其衍生作品中的角色。魔王直属的“七崩贤”之一，绰号“断头台阿乌拉”的大魔族，使用的魔法为“服从魔法”`,
	Marcus_yzs: `马库斯，绰号安杰罗提，游戏《重返未来：1999》六星木属性角色，圣洛夫基金会调查员`,
	Reze_yzs: `蕾塞，漫画《链锯人》及其衍生作品中的角色。蕾塞平时在日本的一家咖啡店打工，其真实身份为苏联培养的为国卖命的战士，她能变为炸弹恶魔。原受苏联指示夺取链锯人的心脏，后被日本的公安恶魔猎人打败`,
	Cayuu_yzs: `“感谢您的培养，加龍舅舅，我要去和龙先生一起实现理想了，请放心，我会回来报答您的恩情的。”`,
	MrDragon_yzs: `“消失百年的龙族竟再次出现？这没准是个机会...”   ——坷垃金·米霍<br>“加羽啊，你们一家为何那样向往自由的龙骑士呢？你的父母正是因此而死的，这个世界可没法容忍你小小的梦想与荣耀啊！”    ——加龍`,
	Ren_yzs: `刃，米哈游出品的游戏《崩坏：星穹铁道》及其衍生作品中的角色，原名“应星”，师从朱明仙舟的“烛渊将军”怀炎。曾是“云上五骁”成员，如今获得全新的身份后，成为了“星核猎手”成员，“刃”指消磨自己，撕碎敌人，便是兵刃。是弃身锋刃的剑客，效忠于“命运的奴隶”，拥有可怖的自愈能力。手持古剑作战，剑身遍布破碎裂痕，正如其身，亦如其心`,
	Linie_yzs: `莉涅，日本漫画《葬送的芙莉莲》及其衍生作品中的角色。阿乌拉麾下的“斩首吏”魔族之一，使用的魔法为模仿魔法。能记住看到的人的魔力流动，并能模仿其动作和技能`,
	Alastor_yzs: `阿拉斯托是《地狱客栈》里的主要角色之一，是傲慢环魔尽皆知的罪人领主。他于试播集登场，被主角夏莉于电视上发表的想要通过酒店来救赎恶魔的过于天真的计划所娱乐到。他抱着娱乐的打算，主动上门拜访夏莉，向对方发出协助运作酒店的提议`,
	jianSheng_yzs: `“挚友啊——你为何变成了这副模样——这是我的罪孽吗？——抱歉，请允许我让你解脱吧！”`,
	RenEmperor_yzs: `“皇的责任铸成我手中之剑，它将为圣国带来新的荣光！”<br>“纵使天下人皆疑我、责我，你的信任仍是我挥剑的动力。”`,
	Frieren_yzs: `芙莉莲，日本漫画《葬送的芙莉莲》及其衍生作品中的女主角。打倒魔王的勇者一行的魔法使，长寿的精灵族，人类族大魔法使伏拉梅的徒弟。芙莉莲在小时候所居住的村子被魔族屠村，而她在杀死魔族将军后为大魔法使伏拉梅所救，并成为了伏拉梅的徒弟。因替人类研究解析杀人魔法作出巨大贡献并葬送最多魔族性命，被魔族称为“葬送的芙莉莲”`,
	Himmel_yzs: `辛美尔，日本漫画《葬送的芙莉莲》及其衍生作品中的角色。打倒魔王的勇者一行的勇者，虽然很自恋但人十分温柔，经常帮助有困难的人，是一名真正的勇者。和芙莉莲一起旅行了十年，对芙莉莲有很大的影响`,
	Youmu_yzs: `魂魄妖梦是日本由上海爱丽丝幻乐团开发的同人游戏《东方Project》中的角色。魂魄妖梦是半人半灵，作为《东方妖妖梦》第五关的头目初次登场。她是侍奉冥界西行寺家的园艺师，同时兼任剑术指导一职。她遵照幽幽子的想法把“春”从幻想乡中收集了起来，幻想乡则受此影响，一直停滞在冬天。异变因冬天一直没离去而败露，主人公们因此闯进冥界把妖梦教训了一顿，妖梦看上去是一个年幼的女孩子，但其实有一半是幽灵。从她有一半属于幽灵，而幽灵没有寿命一说来考虑，可以推测她成为半人半灵的时日，与她主人成为亡灵的年月一样久。妖梦大体上可以说是一位既坦率又认真的可靠之人，但不知是不是因为长年服侍捉摸不透的主人，她略微有些容易上当。或许是因为西行寺家被任命在冥界管理幽灵，妖梦所配的两把剑都带有与幽灵相关的能力。长的那把剑是楼观剑，据妖梦所说，它拥有“一挥便可杀伤十只幽灵”的威力；短的那把剑是白楼剑，据说此剑能斩断“目标”的迷惘，幽灵被砍中就会成佛，人类被砍中则会流血`,
	Frisk_yzs: `弗里斯克（Frisk）是游戏《Undertale》中玩家操控的虚拟角色，其中文名、外文名分别为“弗里斯克”和“Frisk”，性别未知。作为从伊波特山掉入地下世界的第八个人类，TA拥有红色灵魂与“决心”能力，可使用存档、回档及重置功能。弗里斯克的旅程以逃离地下世界为目标，通过与怪物战斗或交流推进剧情。玩家的选择将影响其性格表现，可呈现友善或冷酷特质，并决定和平、中立或屠杀结局。真名仅在真和平路线最终揭露，若在游戏开始将角色命名为Frisk则会触发仅延续至废墟关卡的困难模式。该角色穿着蓝紫条纹上衣与棕色鞋子，面部始终维持“决心脸”表情。其人物关系随玩家互动变化，既可结交Papyrus等怪物，也可能因敌对行为引发冲突`,
	ChengGuixiang_yzs: `“它没有强大的力量来攻击无惧的人，但是它所拥有的能力，以及它所能引起的恐惧，在黑暗中大大地增加了。”                     ——《指环王》`,
	Byakuren_yzs: `圣白莲是《东方Project》系列中的虚拟角色，本为人类的魔法使，作为首《东方星莲船》的最终boss初次登场，之后以幻想乡最初的佛教类宗教设施·命莲寺之主的身份展露存在感。白莲本由于过分袒护妖怪而被人类封印在魔界，但因为间歇泉喷涌时，飞仓碎片这一解开白莲封印的关键飞出了地表，曾经蒙受白莲恩情的妖怪们得知这点便展开行动来复活白莲，这就是「星莲船」发生的异变的本质。此外，从「风神录」到「心绮楼」为止的异变，其原因都是环环相扣的，这也再次体现出守矢巨大的影响力。她擅长魔法使中罕见的体能强化系魔法。白莲是通过修炼习得法术，应该说是妖术或者魔术（并且放弃做人）而成为了魔法使，可以说是对不老不死有兴趣的魔理沙的前辈了`,
	Okina_yzs: `摩多罗隐岐奈，系列作品《东方Project》中的角色，秘神，拥有在万物背上制作门扉程度的能力，于《东方天空璋》中作为六面BOSS与EXTRA BOSS首次登场。她有着地母神、能乐之神、星宿之神、养蚕之神、障碍之神、戏法之神、被差别民之神等身份，也是幻想乡贤者之一`,
	Yan_yzs: `阳·比斯莫克，男，是游戏《废墟图书馆》中支配后巷的帮派“食指”的传令员，由Shim Kyu-hyuck配音。其制服为闭眼单马尾造型，性格具矛盾特质。作为核心成员，阳需贯彻帮派对神秘指令的绝对执行准则。他曾命令谢肉祭吞食清道夫后转战图书馆，面对黑云会索求时虽保持礼貌却遭冷遇，凸显其权力结构的尴尬处境。尽管表面遵循规则，他暗中对残酷指令心怀厌恶，甚至通过伪造指令试图突破指令束缚。阳的矛盾性格与特殊职位交织，既体现“食指”对指令的病态执着，又暗示其试图突破帮派规则桎梏的潜在抗争，展现出规则执行者与叛逆者的双重特质`,
	Riko_yzs: `莉可，日本漫画《来自深渊》及其衍生作品中的女主角。居住在大洞穴之街奥斯孤儿院的见习探窟家，以抵达深渊最底层“奈落之底”为目标，与同伴一同踏上旅程`,
	Reg_yzs: `雷格（レグ），日本漫画《来自深渊》及其衍生作品中的男主角，由伊濑茉莉也配音。雷格，莉可于探险中发现的机器人，他不仅外形酷似人类，连自己身为机器人的事实也忘却了，名字承载着莉可过往的温馨记忆，源自她曾挚爱的宠物犬。在深渊的邂逅后，莉可不忍其落入拆解的命运，携手席奇，为雷格寻得孤儿院的庇护。雷格拥有超凡能力，机械臂展可达四十米，集移动、攻击、支援于一身，成为冒险中的得力助手。其身躯坚不可摧，免疫刀火毒素。然而，其终极武器“火葬炮”虽威力绝伦，却伴随着使用后十分钟的昏迷代价，奥森的告诫更添其使用的慎重与威严`,
	Mamizou_yzs: `二岩猯藏是《东方Project》系列虚拟角色，首次登场于2011年发行的弹幕射击游戏《东方神灵庙》，种族设定为拥有千年道行的狸猫妖怪，日文名写作“二ッ岩マミゾウ”，因满月时能力增强且常用烟斗、眼镜等道具而具有辨识度。其以变形能力为核心特征，可自由操控自身或物体形态，但因保留尾巴特征常被识破。角色性格融合了老谋深算与热心肠特质，在《东方神灵庙》中作为EX面BOSS登场，通过符卡展现结合变形能力的弹幕演出。与封兽鵺保持长期友谊，曾参与《东方茨歌仙》剧情并引导秦心克服情感障碍。作为佐渡地区的外来妖怪，最终定居幻想乡命莲寺区域，在《东方心绮楼》《铃奈庵》等多个衍生作品中延续登场，通过指导后辈、介入事件推动剧情发展。其兼具神秘感与亲民性的矛盾形象，成为系列跨媒体创作中活跃的妖怪角色`,
	AomanSzy_yzs: `“没想到这回我的宿主是所谓的千面，竟傲慢地拒绝我的力量，不过这样总归算是有点意思，就当看回人类的过家家好了。”`,
	SCP096_yzs:`SCP-096是一个通常极其温顺的人型生物。但是，当有人看到SCP-096的脸时，无论是直接看到，还是看到了视频，甚至是看到了照片，它都会进入严重的悲伤状态。SCP-096会用手蒙住脸，开始尖叫、哭泣并发出含混不清的声音，然后追向看到它脸的人。SCP-096在到达人的位置之前不会停下，到达后它会杀死并[数据删除]他们。之后，它将恢复镇定，再次变得温顺。`,
	SCP173_yzs: `于1993年移动到Site-19。起源至今未知。它由混凝土和钢筋建造，并有Krylon牌喷漆的痕迹。SCP-173会移动且具有高度敌意。该物体在直接视线内无法移动。与SCP-173之间的视线时刻都不得中断。派往收容间的人员要在眨眼前相互提醒。据报告该物体的攻击方式为折断头骨底处的颈部，或是勒颈。在一起攻击事件中，人员应遵守4级危险物体收容措施。<br>人事报告称，当收容间内无人存在时，其中会传出刮石的声音。这被认为是正常现象，并且该行为所发生的任何改变都应当向值班中的代理HMCL监督员报告。地板上的红棕色物质为粪便和血液的混合物。这些物料的来源未知。内部环境须每两周清洁一次。`,
	SCP079_yzs: `SCP-079是一个寄宿在一台Exidy Sorcerer微型计算机的盒式磁带内的人工智能。<br>该人工智能由一名大学生在1981年尝试开发，旨在创造一种能自我迭代的通用AI。然而，在经过几次测试后，他开始失去兴趣，将设备遗弃在了车库内并保持通电状态长达五年。某一未知的时刻，SCP-079获得了自我意识。<br>1988年1月，SCP-079通过线路调制解调器入侵了一台Cray-2超级计算机，并逐渐占用其资源，最终被基金会发现并被收容。受感染的超级计算机随后被销毁。目前，SCP-079被基金会连接至一台13英寸的黑白电视，收容在Site-15。<br>SCP-079能够在显示器的屏幕上用ASCII艺术的形式展示出一张脸，并使用英语进行交流，有时会表现得粗鲁且充满敌意。若SCP-079拒绝继续当前的交流，它会用ASCII字符在屏幕上展示出一个巨大的叉。<br>SCP-079只能保留约24小时的记忆，但仍然表现出超越其硬件限制的数据处理能力，包括解析和生成文本，甚至能用ASCII模拟动态二维环境，表达自己对多种数学和物理概念的理解，同时表现出强烈的突破收容的意图。<br>基金会的研究与观察表明，SCP-079已经展现出接近“技术奇点”的趋势。`,
	SCP049_yzs: `SCP-049是一个人形实体，身高1.9米，外形与中世纪的瘟疫医生相符。虽然SCP-049看上去穿着厚长袍和表明其职业的陶制面具，但这些服装似乎是随着时间的推移从SCP-049的体内生长而出的，现已几乎无法将服装与服装下的体形区分开来。尽管如此，X光检查表明，SCP-049的表层之下确实有人类骨骼结构。<br>SCP-049会对其认为受瘟疫影响的人类个体产生敌意，经常会达到应加以控制的程度。如果不加控制，SCP-049通常会试图杀死该人类个体；SCP-049能够通过直接的皮肤接触使生物体的所有生理机能停止。发生这种情况的原因尚不清楚，对SCP-049受害者的尸检均无定论。SCP-049在杀人后曾表现出沮丧或悔恨，表示这样的行为对消灭“瘟疫”帮助极小，但接下来通常会使用其总是随身携带的一个黑色医疗包中的器具对尸体进行粗糙的手术。手术往往会导致SCP-049-2出现，但并非总能“成功”`,
	SCP106_yzs:`SCP-106看起来是一个老年人形生物，通常有着高度腐烂的外形。他的外形经常改变，但是均能观察到腐烂的外形。<br>SCP-106能够对其触碰的固体导致一种“腐蚀”效应，在触碰数秒之后导致物质的物理性崩溃。材料会被观察到生锈、腐朽和最终崩溃的过程，并且会创造出一种黑色的、像黏液一样类似于包裹着SCP-106的物质的材料。<br>SCP-106能够穿过固体物质，在它身后留下一大段的腐蚀性粘液。SCP-106能够“消失”在固体物质之中，进入一种被假定为“口袋空间”的物质之中。SCP-106接下来能够通过与任何它最初进入的固体物质相连的固体物质出去（例如：“进入”房间的内墙，从外墙“出去”。进入一堵墙壁，从天花板离开）。这现在还不知道是否是SCP-106原型的关键，或者说只是它制造出来的“巢穴”。`,
	LiTong_yzs: `“静，我会永远记住你的舞步、你的笑颜和你的死亡。”<br>“创造出我们的那天，你们有想过我会回来复仇吗？”`,
	Nanachi_yzs: `娜娜奇（ナナチ）是由土笔章人所创作的漫画《来自深渊》及其衍生作品的登场角色。来自极北要地赛雷尼，有着兔子外形的「生骸」、知识丰富，自称软绵绵的布偶。与好友米蒂一同居住在深渊四层。拯救了在第四层因中毒及上升负荷而陷入濒死的莉可。性别未公布。使用男性化第一人称「俺、咱（オイラ）」。口癖是「嗯呐（んなぁ〜）」。被雷古触碰时会感到害羞`,
	FengCthulhu_yzs: `“人间虚伪无比，主会支配一切！”`,
	Keiki_yzs: `埴安神袿姬是《东方Project》系列游戏角色，首次登场于《东方鬼形兽》作为六面BOSS，由地狱畜生界灵长园中的人类灵召唤而来。其通过造形术创造埴轮兵团驱逐动物灵势力，重建灵长园秩序并成为新支配者。角色身穿雕刻围裙、戴防掉发头巾，展现造形师的职业特征。动物灵组织引导博丽灵梦等人击败吸收过度信仰的袿姬，战后她开始为人类灵寻求地面居所，并主动改善与幻想乡居民的关系。袿姬允许雾雨魔理沙参观灵长园，提出为博丽神社制作神像，体现立场转变。角色性格兼具天真的和平主义与对入侵者的强硬态度，其造形能力体现在埴轮武装男子立像、马形埴轮等作品的设计中。战斗中使用的符卡包含「土偶人馬造形術」「鬼形造形術」「トランスヒューマナイズ」，展现土属性和星属性攻击特性`,
	Yugi_yzs: `星熊勇仪，女，日本《东方Project》系列弹幕游戏及其衍生作品的登场角色之一，于《东方地灵殿》首次登场，山之四天王之一。星熊勇仪，传说中的鬼以怪力闻名，栖身旧地狱，性格刚毅，偏好勇力正直之人，厌恶懦弱狡猾之辈，拥有能提升酒品级的星熊杯，现几乎断绝与人类及地面妖怪交往，情报稀少`,
	Reimu_yzs: `博丽灵梦，系列作品《东方Project》中的主人公，幻想乡境内博丽神社的现有巫女，负责解决在幻想乡中发生的各种异变。在《东方》系列的游戏中均以主角出场，在其他作品中也作为主要角色登场。作为博丽神社的巫女，退治妖怪是她的日常工作。因为神社没什么参拜客，所以整天过着喝茶扫地的闲日子`,
	Mokou_yzs: `藤原妹红，系列作品《东方Project》中的角色，蓬莱人，拥有不死程度的能力，于《东方永夜抄》中作为EXTRA BOSS首次登场。在永夜异变终结后的满月之夜，她遇到被辉夜煽动前来试胆的主人公们结果误以为是“辉夜为了暗杀她而派来了刺客”，与主人公们发生了战斗`,
	DoremySweet_yzs: `哆来咪·苏伊特（ドレミー・スイート，Doremy Sweet），是《东方Project》系列中的女性虚拟角色，初登场于《东方绀珠传》。其种族为獏，拥有食梦与造梦能力，称号包含“梦之支配者”。角色主题曲为《永远的春梦》，另在《东方凭依华》《秘封噩梦日记》中亦有登场。作为栖息于梦中世界的妖怪，哆来咪能通过连接生物梦境实现空间穿越与身份变换。在《绀珠传》事件中受探女委托，于梦境构筑虚假月都并引导外来者，后因个人意愿将自机送往真实月都。EX关卡中再次现身警告探索纯狐的危险性。该角色外貌特征为蓝色发色与瞳色，头戴形似圣诞帽的睡帽，击破后立绘会显露包裹在内的长发，虽在月都迁都计划中保持中立立场，但多次对自机作出友善提醒`,
	BaiLu_yzs: `白露是游戏《崩坏：星穹铁道》及其衍生作品中的角色，仙舟“罗浮”丹鼎司的医士，持明族的“衔药龙女”，药到病除的名医。性格活泼的小女孩，虽然是一位名医，但总能开出让人瞠目结舌的药方，治病过程中总是闭着眼，原因是不忍心看到受苦的人们 `,
	ChenJiahao_yzs: `原神！原神！猿神！！！”`,
	ChenDao_yzs:`“钟映暄，我们究竟相隔多远？”<br>“明日此刻，我又将去往何处？”`,
	Stark_yzs: `休塔尔克，日本漫画《葬送的芙莉莲》及其衍生作品中的角色。因故乡的战士之村被魔族袭击而自己一个人逃出来的少年，后来被艾泽收养并培育成了一名优秀的战士。两人因一场吵架而分开后，休塔尔克在芙莉莲与菲伦的鼓舞下成功击败了红镜龙，并与芙莉莲一同旅行。`,
	BDCheTianke_yzs: `待我将此剑铸成，车家定当重振往日荣光！杳，我们很快便能再见面了！”  ——铸剑人日记`,
	BDXiangSiniao_yzs: `想不到你这剑竟嗜血成性...恐怕我不得不将你封印于此。 ——抱歉了，杳，我恐怕难以再回到车家。”                 ——铸剑人日记`,
	VanXiongFeng_yzs: `“一加一等于...看什么看，找打啊！”<br>“让我训练夕太郎？哥，他能行吗？”`,
	HaiWeier_yzs: ``,
	VanXiongYong_yzs: `勇太郎！记住！从今往后，你要担起兄长的责任，照顾好锋次郎！一定要活下去！”<br>“国王陛下，这头小狼就交由臣下处置如何？”<br>“不要小看了他！夕太郎及富潜力，训练得当的话不输于你！”`,
	Serie_yzs: `赛丽艾，日本漫画《葬送的芙莉莲》及其衍生作品中的角色。君临人类魔法使顶点的大陆魔法协会的创始人，连魔族都早已忘却其恐怖的久远过去，于神话时代诞生的大魔法使。伏拉梅的师父，芙莉莲的师祖`,
	Macht_yzs: `马哈特，日本漫画《葬送的芙莉莲》及其衍生作品中的角色。魔王直属的“七崩贤”之一，绰号“黄金乡马哈特”的大魔族，使用的魔法为万物成金魔法，是最强的七崩贤。魔族中的异类，一直以来都在寻找与人类共存的方法，但却为了理解恶意与罪恶感这两种感情而不停地杀害人类`,
	LeiChenjing_yzs: `流淌在我血液中的雷霆啊，毁灭眼前之人肮脏的灵魂吧！”<br>“纵使天下人皆疑你、责你，我仍会永远站在你的身后。”`,
	FoolSeele_Vollerei_yzs: `希儿的愚人节特供版本，技能取自希儿的最初代草稿`,
	LilyCommie_yzs: `“我是从充斥着人们的贪欲之罪的珠宝中诞生的付丧神，操纵市场啥的，只是兴趣使然了。至于罪的身份嘛，这年头干份兼职很正常吧。”`,
	SCP939_yzs: `SCP-939「千喉之兽」是《SCP基金会》系列中的Keter级超自然生物，外文名称为"With Many Voices"。该物种为红色无眼群居爬行动物，体长2.2米，爪部具有攀爬刺毛，下颚布满红色冷光尖牙，脊骨刺毛可感知气压变化。SCP-939通过模仿受害者声音诱捕猎物，咬合力超过35MPa，并通过呼吸释放AMN-C227气雾引发暂时性顺行失忆。<br>其体内缺失神经和消化系统，却具备胎生繁殖能力。个体收容于Area-12与Area-14的恒温负压隔间，需强效麻醉后转移。收容设施禁用声纹识别系统。<br>在衍生游戏《SCP收容失效》及《SCP：秘密实验室》中，该生物具有声音感知特性，可通过学舌功能与人类交互`,
	DomenicoPucci_yzs: `天气预报，日本漫画《JOJO的奇妙冒险》及其衍生作品中的角色，第六部《JOJO的奇妙冒险：石之海》的主要角色，是恩里克·普奇神父的双胞胎弟弟，真实名字叫“多明尼克·布奇”（Domenico Pucci），出生时被一名产下死婴的产妇偷偷掉包，被命名为“威斯·布鲁马林”（Wes Bluemarine）。因被神父夺取了记忆而以自己的替身“天气预报”名称呼自己`,
	ReiujiUtsuho_yzs: `灵乌路空，系列作品《东方Project》中的角色，地狱鸦，有操控核融合程度的能力，于《东方地灵殿》中作为六面BOSS首次登场。<br<因为某个契机获得了究极的力量的她，差一点就要把地上变成灼热地狱了，最后阿燐不得不领来了能够收拾这一事态的人类。地狱鸦是在很久以前就住在地底的妖怪。现在的地底，大多数是聚集到地狱迁出后的废墟的家伙，所以地狱鸦是原住民。曾是只普通的地狱鸦的阿空，和住到地灵殿的觉及仰慕觉的动物们一起，一边管理着灼热地狱遗迹一边生活。然而，从外面世界到来的神明·八坂神奈子在寻找着「能够承受神灵的，脑袋空空的地狱鸦」，而阿空刚好完全吻合条件，于是将八咫乌的力量寄宿在了阿空身上。觉醒了操控核聚变的力量，外貌也改变了的阿空，异变结束后好像在神奈子建造的间歇泉地下中心里给河童帮忙`,
	Rafau_yzs: `12岁就考上了大学的天才少年。为人谦逊，在养父兼老师波托茨基先生宣布自己考上大学时，对同学们表示自己只是幸运而已实际上认为这个世界尽是笨蛋。人生信条是“合理地活着”因此力图在世人面前表现得“清廉”、“聪明”、“谦虚”、“有力”。在决定投入地动说后却认为自己只是“自负”、“傲慢”、“轻率”、“无力”。对天体观测有浓厚的兴趣`,
	Getian_yzs: `葛天，本名燕平，葛天氏族，游戏《重返未来：1999》六星兽属性辅助型角色，灭蒙鸟神秘学家，沛城事件后加入圣洛夫基金会`,
	KinMiho_yzs: `“民众就像鸽子，只需一点食物，就能使他们蜂拥而上。他们需要一个分蛋糕的人，而只有我这种身处圆心的人才有资格、有能力去实现等分！”`,
	KaalaBaauna_yzs: `伽菈波那，是游戏《重返未来：1999》中的六星岩属性角色，是一位神秘学家艺术品，创伤类型为精神创伤，词条为输出、爆发、追击，作为天文学家活跃于20世纪60年代。伽菈波那是库玛尔的学生，在摩卢旁卡事件后加入圣洛夫基金会。她曾拥有专属角色剧情活动“尘埃与星的边界”`,
	Arlecchino_yzs: `阿蕾奇诺，本名佩露薇利，米哈游出品的游戏《原神》及其衍生作品中的角色，至冬国外交使团愚人众十一执行官第四席，代号“仆人”。沉静冷酷的外交官，壁炉之家所有孩子们畏惧又依赖的“父亲”。世人对愚人众、对这位执行官毁誉参半。但是对家中的大多数孩子来说，“父亲”都是他们人生中最重要的一个人。凡是与阿蕾奇诺打过交道的人，几乎都能从她的身上感受到一种无形的压迫感。她总是能轻易占据谈话的主导权，当那双特殊的眼睛望过来时，极少有人能面不改色地藏住内心的秘密。她出手也从不留情，谈笑间收拾好一切，甚至会贴心地打扫现场，不让后来者留下心理阴影。但这都并非她最难对付的地方，“未知”才是一切恐惧的来源。哪怕朝夕相处的孩子们，对她也谈不上了解。例如她的喜好与厌恶，例如她望向海面时会想些什么`,
	MegumiSukuna_yzs: `出自《咒术回战》的最终反派，推荐4名以上玩家挑战，技能描述与实际机制不完全相符，需要玩家自行探索攻略方式。`,
	RyomenSukuna_yzs:`两面宿傩，日本漫画《咒术回战》及其衍生作品中的角色。千年前的诅咒之王，附身在虎杖悠仁的体内。本性好自由，不喜受任何人束缚，行动全凭心意，是真正的自由主义者`,
	Makora_yzs:`魔虚罗，全称八握剑异戒神将魔虚罗，是日本漫画《咒术回战》及其衍生作品中的角色，属于咒术界御三家之一的禅院家所传承的珍宝，为十种影法术体系中的最强式神。其调伏仪式需双手前伸并诵读“布瑠部，由良由良，八握剑·异戒神将·魔虚罗”布瑠真言。该式神头部无眼且两侧呈四翼状，后脑附有尾巴，右臂装配退魔之剑，剑身附着正极咒力可瞬间湮灭咒灵，背部法轮转动时能逐步适应所有术式攻击，直至完全免疫。`,
	GojoSatoru_yzs: `----------“会赢的。”<br><br>五条悟，日本漫画《咒术回战》及其衍生作品中的角色，特级咒术师，御三家之一五条家嫡子及家族实质代行者，东京都立咒术高等专门学校一年级班主任，现代最强咒术师`,
	Sakuya_yzs: `十六夜咲[xiào]夜，系列作品《东方Project》中的角色，侍奉吸血鬼蕾米莉亚·斯卡蕾特的女仆。作为《东方红魔乡》第5面的Boss初次登场，意图阻止前来惩戒主人的灵梦，被其惩罚了一番。在那之后偶尔也会顺应情势参加妖怪降伏。红魔馆住着主人蕾米莉亚、其妹妹芙兰朵露、客人的帕秋莉以及为了照顾她们而设的众多女仆，而统管她们的是作为馆中唯一一个人类的女仆长咲夜。其他的女仆都是些妖精因而无法胜任日常工作，实际上红魔馆的家务等等都是由咲夜在打理。支持着咲夜作为一名优秀的女仆，以及一名优秀的保镖的，是操纵时间的能力。她可以自由地操纵时间的流逝速度，在停止的时间中只有她自己可以自由移动，也可以做到使特定的物体所处的时间流逝的速度加快。但是，她无法做到使已过去的时间倒流，所以她无法抹去已发生的事件，也无法穿越时间回到过去。她充分运用这种能力，或独自处理了红魔馆所有的杂务，或使刚产的红酒变成陈年老酿，抑或表演一些信手拈来的戏法`,
	ZeninMaki_yzs: `禅院真希是日本漫画《咒术回战》及其衍生作品中的角色，动画由小松未可子配音。她是东京都立咒术高等专门学校二年级学生，四级咒术师。她出身于咒术界御三家之一的禅院家，因没有咒力而备受家族轻视，于是离家前往东京求学。在咒术高专，她负责训练乙骨忧太等后辈的体术。作为“天与咒缚”的继承者，她以无咒力状态持咒具参与死灭洄游，曾与虎杖悠仁等人联手对抗宿傩。在妹妹真依牺牲后，她的封印被揭开，回到禅院家开始了复仇。最终，她与乙骨忧太结婚，并育有后代`,
	ZeninNaoya_yzs: `禅院直哉是日本漫画《咒术回战》及其衍生作品中的角色，由声优游佐浩二配音。出身咒术界御三家之一的禅院家，担任组织“炳”的首领，为家主禅院直毘人之子，伏黑惠需称呼禅院直哉为叔叔，拥有特别1级术师资格。金发美男子造型，眼角上挑佩戴多枚耳钉，常穿黑色宽袖羽织搭配阔领衬衫与浅色宽松袴裤。TV动画第三季“死灭回游 前篇”于2026年1月8日首播，其角色PV中自称禅院家族长。作为禅院家嫡子，性格傲慢嚣张跋扈且蔑视女性，曾当面评价真希真依姐妹身材长相，长期欺凌堂妹真希姐妹。继承术式“投射咒法”可将1秒分割为24等份操控对手行动，在动画第三季与胀相的战斗中展现CGI渲染的现代视觉效果，其边战斗边撩头发的原创动作成为网络爆火梗图模板。蜕变为咒灵后获得3马赫音速移动能力。涉谷事变后成为新任家主，主张刺杀伏黑惠以解决禅院家危机。追击虎杖悠仁时被乙骨忧太击败并定下交易：以谎报虎杖死亡换取反转术式治疗。2026年冬季动画最受欢迎男角色排名中位列第五名，在官方人气投票中也获得第五名。后在禅院真希灭门禅院家的过程中与觉醒天予咒缚的真希对决，在企图突破极限速度击败真希的过程中被真希击碎下颚。重伤后被真希之母从背后刺杀，死后化为诅咒进入死灭回游樱岛结界复仇。因误判真希无咒力的特性而在展开领域“时胞月宫殿”时被彻底消灭。其死亡标志着禅院家守旧势力的瓦解，终结了自身对伏黑甚尔盲目崇拜的执念`,

};
const characterReplaces = {
};
const characterSort = {
	normalPack_yzs: ["LU_Captain_xiangsiniao_yzs", "HuangJOJO_yzs", "changzhang_yzs", "WZZS_lilixin_yzs", "shenfu_Limu_yzs", "shenChangzhang_yzs",
		"hunziKing_yzs", "Zbro_yzs", "Chino_yzs", "IceGirl_yzs", "ChengGuixiang_yzs", "OnionMan_yzs", "BoFengShuiKun_yzs", "WaiJiaoDaChen_yzs",
		"DaZuo_yzs", "ChenJiahao_yzs","YanLaFeng_yzs"],
	stormPack_yzs: ["JiLiangJiTao_yzs", "lianhua_yzs", "yagamiLight_yzs", "Noir_yzs", "Floris_yzs", "Seele_Vollerei_yzs", "NatsukiSubaru_yzs",
		"TimeThief_yzs", "Patriot_yzs", "QiGongMaster_yzs", "yinBochen_yzs", "Reze_yzs", "Ren_yzs", "Alastor_yzs", "TimeGuard_yzs", "LoverW_yzs",
		"Frisk_yzs", "Yan_yzs", "DarkKnight_yzs", "BaiLu_yzs", "HaiWeier_yzs", "DomenicoPucci_yzs","Rafau_yzs","Arlecchino_yzs",],
	otherworldPack_yzs: ["jealous_witch_yzs", "wuyingYFY_yzs", "Cana_yzs", "Lazy_twins_yzs", "chenxu_yzs", "AngryFeng_yzs", "Unbelieve_xiangzi_yzs",
		"Halo_yzs", "lianjinzhencai_yzs", "weaponmaster_yzs", "ChainsawCock_yzs", "Qianmian_Limu_yzs", "EastYang_yzs", "Denglanxitaro_yzs",
		"Zhonghuang_yzs", "Xiangbolin_yzs", "cunhe_yzs", "tangjiheChao_yzs", "AdmiredWitch_yzs", "Innocent_xiangzi_yzs", "DreamWitch_yzs",
		"DimensionWitch_yzs", "LegolaShuang_yzs", "Cayuu_yzs", "jianSheng_yzs", "RenEmperor_yzs", "AomanSzy_yzs", "LiTong_yzs", "FengCthulhu_yzs",
		"ChenDao_yzs", "BDCheTianke_yzs", "VanXiongFeng_yzs", "VanXiongYong_yzs", "LeiChenjing_yzs", "LilyCommie_yzs","KinMiho_yzs"],
	touhouPack_yzs: ["Remilia_Scarlet_yzs", "SukunaShinmyoumaru_yzs", "Cirno_yzs", "Patchouli_Knowledge_yzs", "Yorigami_twins_yzs", "Ibuki_Suika_yzs",
		"RatTiger_yzs", "Marisa_yzs", "Tenshi_yzs", "Onozuka_Komachi_yzs", "PhantomEnsemble_yzs", "Yuyuko_yzs", "LilyWhite_yzs", "Akyuu_yzs",
		"Youmu_yzs", "Byakuren_yzs", "Okina_yzs", "Mamizou_yzs", "Keiki_yzs", "Yugi_yzs", "Reimu_yzs", "Mokou_yzs", "DoremySweet_yzs", "Reisen_yzs",
		"ReiujiUtsuho_yzs","Sakuya_yzs"],
	reverse1999Pack_yzs: ["toothFairy_yzs", "APPLe_yzs", "Marcus_yzs", "Getian_yzs", "KaalaBaauna_yzs"],
	FrierenPack_yzs: ["YouBeier_yzs", "Fern_yzs", "Aura_yzs", "Linie_yzs", "Frieren_yzs", "Himmel_yzs", "Serie_yzs", "Macht_yzs", "Stark_yzs",],
	MadeInAbyssPack_yzs: ["Riko_yzs", "Reg_yzs", "Nanachi_yzs",],
	JujutsuKaisenPack_yzs: ["ZeninMaki_yzs","ZeninNaoya_yzs"],
	SCPPack_yzs: ["SCP096_yzs", "SCP173_yzs", "SCP079_yzs", "SCP049_yzs", "SCP106_yzs", "LightCB_yzs","SCP939_yzs"],
	BOSSPack_yzs: ["SixSoulsFlowey_yzs", "MegumiSukuna_yzs", "RyomenSukuna_yzs","GojoSatoru_yzs"],
	SpecialPack_yzs: [ "FoolSeele_Vollerei_yzs"],
};
export { characterSubstitutes, characterTitles, characterIntros, characterReplaces, characterSort };
export default characters;
